### ISSUE TITLE
Support encrypted Realm files in the Browser

### ISSUE THREAD

**Issue by TimOliver** [realm/realm-browser-osx#11]
_From @alazier on January 6, 2015 19:6_

null

_Copied from original issue: realm/realm-cocoa#1300_

**Comment by TimOliver** [comment]
_From @cfeckardt on April 19, 2015 23:8_

I have a mostly working patch for this and will make a PR in the next couple of days.

**Comment by TimOliver** [comment]
_From @bigfish24 on May 21, 2015 20:20_

@cfeckardt were you able to finish the patch for this?

**Comment by natanrolnik** [comment]
+1 - that's very important

**Comment by TimOliver** [comment]
Implemented in #https://github.com/realm/realm-browser-osx/pull/74
