### ISSUE TITLE
Add Link to Object not working

### ISSUE THREAD

**Issue by sprint84** [realm/realm-browser-osx#111]
When I select the option to add a link to an existing object, it opens a list of objects of the same type, but I can't select one of them. Double-clicking or hitting return prompts to edit one of the fields.

**Comment by ReDetection** [comment]
Hi @sprint84 ! One click is enough.
I was the guy who write this feature. Just checked it with latest version of realm browser from the appstore — still working. Can you provide any additional info? Maybe the (almost empty) database file?

**Comment by TimOliver** [comment]
I'm just doing some spring cleaning on these older issues. Thanks for clarifying the behaviour @ReDetection! 

@sprint84 If you have any further queries, please feel free to either re-open this issue and follow-up, or start a new issue. Thanks! :)
