### ISSUE TITLE
In Realm browser copy and paste only works with the right-click context menu.

### ISSUE THREAD

**Issue by TimOliver** [realm/realm-browser-osx#12]
_From @webmagnets on January 4, 2015 20:48_

In the Realm browser I am unable to copy with &#8984;-c or paste with &#8984;-p. It works if I right click and then choose one of those options from the context menu.

Thanks for all your hard work guys (and girls?)!

p.s. - Just in case someone is searching for this issue, var &#8984; = "command" // :smile: 

_Copied from original issue: realm/realm-cocoa#1295_

**Comment by TimOliver** [comment]
_From @GreatApe on January 5, 2015 13:36_

Hello, this is because the copy functionality you describe comes from OSX, not the Browser. And I presume they didn't bind the keys because the underlying apps will want to do that. In any case, the Browser itself does not currently have copy-pasting, and when it is introduced there will be at least two different kinds: 

1. Copying text (and possibly other media) inside individual cells/properties.
2. Copying entire objects or sets of objects.

Since 2 is probably more important, the key bindings might reflect that, or it might be that CMD-C should do different things depending on what is selected. Unless that is too confusing. We might consider binding CMD-C to text copying within cells for now though if this is a major inconvenience.

The short answer is that what you observed is expected behaviour!

**Comment by TimOliver** [comment]
_From @webmagnets on January 8, 2015 15:23_

IMHO: I think text copying should be cmd-c and object copying should be some other combo.

**Comment by TimOliver** [comment]
_From @mrh-is on February 13, 2015 18:42_

+1 for this feature.

IMHO: Copy whatever is selected, Excel-style. If the row is selected, copy the object; if the text in a cell is selected (by double clicking), copy the text. (Same for paste.)

**Comment by jakecraige** [comment]
Ran into this today and thankfully came across this issue so I could do it. Excel-style copying makes sense.

For full MVP-ish-ness, I'd be completely happy if when you were editing a column and select the text if Command-C and Command-V would work. 

Thanks for this sweet db browser!

**Comment by TimOliver** [comment]
Hi @jakecraige!

Thanks for that! Yeah, I've been exploring adding the Cut/Copy/Paste menu options back in, and then making them contextually away of copying cells, as well as copying cell values. It's definitely something that would make the experience of the Browser a lot better!
