### ISSUE TITLE
Not showing complete string in pk

### ISSUE THREAD

**Issue by foobar8675** [realm/realm-browser-osx#123]
if you look at the screenshot, the id column has a string temptestchild1_2016-01-26 08:32:28 +0000; where in the browser, it shows temptestchild1_2016-01-26

running Version 0.97.0 (62)
 
![screen shot 2016-01-30 at 9 01 11 am](https://cloud.githubusercontent.com/assets/1685700/12697121/163ee032-c730-11e5-96a8-90d64a2ecd69.png)

**Comment by TimOliver** [comment]
Hi @foobar8675!

When text is too long in the text fields, it wraps downwards. If you click and drag downwards, you should be able to see the rest of your text.

Alternatively, you can also make the column wider. :)

We're still refining how the Realm Browser renders content, so if you've got any other suggestions on how it should work, please let us know! Thanks!

**Comment by foobar8675** [comment]
in google sheets (or excel) , when i mouse over a dividing line in the column, the cursor changes to let me know i'm in a state where i can resize the column.

as it's been noted by a few other people, i'm a big fan of the data export to csv, that i believe you are working on.

**Comment by TimOliver** [comment]
It does if if you mouse over the region where the divider line should be in the header bar. Admittedly we should probably make that a bit more obvious.

Haha that's correct! I'm working on the finishing touches for it now. Hopefully we can make it go public this week. :)

(Thanks a lot! It's still definitely a heavy work in progress so we really appreciate the feedback! :) )

**Comment by foobar8675** [comment]
i know you were asking for feature requests, the ability to sort by clicking the name of the column would be handy.
