### ISSUE TITLE
CSV Import

### ISSUE THREAD

**Issue by grahamsmith** [realm/realm-browser-osx#127]
Following a comment on a java realm Github.com issue 

https://github.com/realm/realm-java/issues/2241#issuecomment-184304396

The idea here is that demo data could be stored in a CSV file and imported via the browser. 

It would be good to see the creation of new classes and to upsert existing data. 

This would be great for testing if combined with commandline tools to create dummy datasets. 

To give some context, currently I generate a test database file in a basic Android App. This is not the ideal medium as it makes it harder to work with Jenkins and other CI tools. Doing something similar to the above would mean specific commands could be given and mock database file produced and stored somewhere.

**Comment by TimOliver** [comment]
@grahamsmith Thanks for the issue!

We've got an issue tracking formats we want to support here: https://github.com/realm/realm-browser-osx/issues/34

At the moment, I'm putting the finishing touches on a module to allow importing CSV data into a new  Realm file and exporting it again (But not appending data to existing Realm files just yet).

I'm hoping to release it this week. :)

**Comment by TimOliver** [comment]
Hi @grahamsmith!

We've included a CSV importer into the later versions of Realm Browser. Please have a try and let me know what you think!

https://github.com/realm/realm-browser-osx/releases/tag/0.98.6

Thanks!

**Comment by ianwhite2** [comment]
@TimOliver  I don't think so Import csv is working

**Comment by StefanoOrdine** [comment]
@TimOliver I'm trying to import from a csv file with 500 lines 
```
id,name
0,A
1,B
...
```
It crashes, but like with 250 rows it does the job. Is there a way to import my 40K rows csv file with this tool?

**Comment by TimOliver** [comment]
Hey @StefanoOrdine! When it crashes, what is the error it gives you exactly?

**Comment by StefanoOrdine** [comment]
It gives no error just the application does not respond anymore. I can provide the full stack trace in a gist if required :-)

**Comment by TimOliver** [comment]
Sure! That would definitely help! :)

**Comment by StefanoOrdine** [comment]
I create a Gist for this: 

https://gist.github.com/StefanoOrdine/bfc4d50ed4f0661b7dc60445a55b2cab

If there is anything more I can add to provide you more help just ask
