### ISSUE TITLE
'Add new object to array' not working

### ISSUE THREAD

**Issue by vualeks** [realm/realm-browser-osx#130]
Hi,

I've just created a simple db that has object with a RealmList array field. It says in browser that array is empty (has 0 objects). Right click and selecting 'Open array in new window' opens a window to add new objects to this array. Right click on the table allows to 'Add new object to array' and when I click it, it creates a new object of that kind in its table, but it doesn't link it to this array (it still remains with 0 elements). Adding any new elements to array always creates them, but no link to the array. Am I missing something or is this a bug?

Anyway, I tried this with browser version Version 0.97.0 (62).

Thanks for your work,

Best regards,

Aleksandar

**Comment by trustyfrog** [comment]
I'm getting this, at least with the App Store version. I see the count for objects of that type go up but I just can't insert the new object.

**Comment by trustyfrog** [comment]
@vualeks As a temporary measure, if you create a row programatically then the browser lets you add additional rows thereafter.

**Comment by vualeks** [comment]
Well, It's not particularly useful because adding every new object that also has lists inside will have empty list and then I'll be unable to new object to that newly created list. Anyway thanks, but I guess I'll have to wait for a bug fix for this :)

**Comment by jpsanabria** [comment]
I'm also having this issue.. Downloaded from Mac Store
