### ISSUE TITLE
help me export file .realm to .csv ?

### ISSUE THREAD

**Issue by kuteteen** [realm/realm-browser-osx#135]
help me export file .realm to .csv ???

**Comment by TimOliver** [comment]
Hi @kuteteen! Sorry for the delay!

I pushed a pre-release version of the Browser featuring our new CSV exporter to the GitHub releases last week: https://github.com/realm/realm-browser-osx/releases/tag/0.98.3

Please have a look at that and tell me if you think it needs anything else! Thanks! :)

**Comment by TimOliver** [comment]
We haven't heard anything from this issue for a while, so I'm closing it. If you wish to follow up, feel free to re-open it! :)
