### ISSUE TITLE
Consider keeping (/scrolling to) selection after Find is closed

### ISSUE THREAD

**Issue by DanielAsher** [realm/realm-browser-osx#136]
I often search for an item (within 130,000), select it, then close (/cancel?) the `Find`. I would expect my selection would remain after `Find` is closed and the selection would be visible.

Currently cancelling a `Find` returns me to the first item in the table.

**Comment by TimOliver** [comment]
Hi @DanielAsher! 

Thanks for that! I'll see if I can have a look at making the scroll position stick. :)
