### ISSUE TITLE
Caskroom Support

### ISSUE THREAD

**Issue by chrisamanse** [realm/realm-browser-osx#137]
Can you support installation of Realm Browser using [caskroom](https://caskroom.github.io)?

**Comment by TimOliver** [comment]
Hi @chrisamanse!

Interesting! I've never heard of Caskroom before. What sort of advantages would it give over the App Store or (as we're potentially investigating it) the Sparkle framework?

Thanks!

**Comment by chrisamanse** [comment]
I'm new to Caskroom as well.

Well, Sparkle would be more user-friendly. However, for those who are fond of installing tools through the command line, it would be convenient to install or update Realm Browser just by running a terminal command (assuming [homebrew](http://brew.sh) is already installed). On the other hand, App Store updates would lag behind GitHub releases.

As of now, without Sparkle support, I think caskroom would be a great alternative for installing and updating the app :)

**Comment by vitorgalvao** [comment]
Sparkle and homebrew-cask (caskroom is the organisation) aren’t mutually exclusive. Sparkle allows you to auto-update your app, while homebrew-cask allows you to install it by using the command line. They’re different things.

**Comment by jpsim** [comment]
Since the browser is open source, why not use Homebrew proper instead? A few OSS OS X apps do this already.

**Comment by jpsim** [comment]
Also, the caskroom formula you posted has a number of issues, first of which is the lack of signature verification.

**Comment by vitorgalvao** [comment]
@jpsim Because homebrew is more geared towards CLI apps and homebrew-cask towards GUI apps, and [as we bring the projects closer together](https://github.com/caskroom/homebrew-cask/issues/14384), [that divide will be even more pronounced](https://github.com/caskroom/homebrew-cask/issues/15603#issuecomment-162168106).

**Comment by chrisamanse** [comment]
@jpsim I'll update the Cask in my PR.

@vitorgalvao If the app, for example, is updated using Sparkle, will homebrew-cask also recognize the update?

**Comment by vitorgalvao** [comment]
@chrisamanse https://github.com/caskroom/homebrew-cask/issues/13201. Homebrew-cask won’t care. It won’t stop the app from doing what it does and updating automatically.

**Comment by chrisamanse** [comment]
Just added `realm-browser.rb` in homebrew-cask (caskroom/homebrew-cask@c023d767b3c16462f1c90148cf35ff456faacd33)

We can now install realm browser by running `brew cask install realm-browser`. You may also need to update the casks info repo by running `brew cask update`.

**Comment by phatblat** [comment]
FYI, I submitted caskroom/homebrew-cask#39852 to add [Realm Studio](https://realm.io/products/realm-studio/) to Homebrew cask. Not sure if there's a way to deprecate the Browser's cask.
