### ISSUE TITLE
Use tabular (monospaced) font for numbers

### ISSUE THREAD

**Issue by duemunk** [realm/realm-browser-osx#138]
Currently the number are shown using a font(setting) with proportional numbers. This leads to the following changing margin as seen in the screenshot:
![screen shot 2016-03-09 at 11 32 53](https://cloud.githubusercontent.com/assets/489138/13632591/b48f67d8-e5ea-11e5-8f5c-940586efd60e.png)

If it was changed to use tabular (monospaced) it would be easer to compare numbers in a column as well as prettier.

**Comment by TimOliver** [comment]
Hi @duemunk!

Sorry for the delay! That's an awesome idea! Thanks for that! I'll look into seeing how we can add that in!

Thanks! :)
