### ISSUE TITLE
Update data model generation to support primary key annotations for Java

### ISSUE THREAD

**Issue by mikemee** [realm/realm-browser-osx#140]
1. build a realm database from Swift that includes the following:
```
    dynamic var id:Int = -1
    // other fields

    override class func primaryKey() -> String {
        return "id"
    }
```
2. Open the resulting database in the Realm Browser
3. Chose File -> Save Model Definitions -> Save Java Definitions...

Expect: Resulting model file will have the @PrimaryKey annotation like:
```
    @PrimaryKey
    private int id;
    // other fields
```

Actual: Model file has no annotation:
```
    private int id;
    // other fields
```

_Note: I'm not sure how primary keys are indicated for Objective-C, but I took a quick look and didn't see anything special there either, so perhaps an issue for ObjC generation too._

**Comment by TimOliver** [comment]
Hi @mikemee!

Sorry for the delay. We updated our model generation code in the Browser relatively recently, and there is now functionality to handle primary keys on the Java side.

I cut a new release of the Browser yesterday. Can you let me know if you're still having that trouble in that release? https://github.com/realm/realm-browser-osx/releases/tag/0.98.6

Thanks a lot!

**Comment by mikemee** [comment]
Hi @TimOliver!

I now see `@PrimaryKey` annotations.  Cross this one off the list. Many thanks!
