### ISSUE TITLE
Unsupported version

### ISSUE THREAD

**Issue by miff** [realm/realm-browser-osx#141]
<img width="426" alt="screen shot 2016-03-13 at 00 31 18" src="https://cloud.githubusercontent.com/assets/469459/13725966/f787ba2a-e8b2-11e5-9dd9-e4176cb127fb.png">

Am update to the latest RealmSwift and Realm Browser and then start to fire this error, how to solve this?
Thanks,
Milan

**Comment by thejojo87** [comment]
me too,after i updated realm by 0.98.4. i cannot open realm data by browser.

**Comment by miff** [comment]
@thejojo87 try to restart, but the problem continue https://github.com/realm/realm-cocoa/issues/3321, it's crash on some older devices

**Comment by TimOliver** [comment]
Hi guys! It looks like we might have had a slight hiccup when we released Realm 0.98.4, so we released Realm 0.98.5 today.

I just put up a new build of the Browser incorporating 0.98.5 here: https://github.com/realm/realm-browser-osx/releases/tag/0.98.5

Could you please test that and see if it fixes that issue for you? Thanks!

**Comment by miff** [comment]
It's working now :+1:

**Comment by TimOliver** [comment]
Awesome! Thanks for that! I'll be sending that version off to the App Store very shortly!
