### ISSUE TITLE
Generate JavaScript Data Models

### ISSUE THREAD

**Issue by astigsen** [realm/realm-browser-osx#144]
Now that Realm is also available for React Native, the browser should have the ability to generate Data Models for JavaScript as well.

**Comment by TimOliver** [comment]
Good idea! I'll look into that! :)

**Comment by ksibod** [comment]
I've made a pull request for this feature:
https://github.com/realm/realm-browser-osx/pull/272

**Comment by stel** [comment]
Merged! Thanks again, @ksibod!
