### ISSUE TITLE
Realm Browser seems to be not able to open compressed realm files

### ISSUE THREAD

**Issue by kishikawakatsumi** [realm/realm-browser-osx#145]
Cross-posted from realm/realm-cocoa#3338 /cc @victor-kotov-arcadia .

## Goals

I have realm backup copy of the realm DB. I'm trying to open it with Realm Browser app for Mac OS X.

## Expected Results

DB opened and I'm able to check data and structure.

## Actual Results

Realm Browser crashed and next launch it's saying "File encrypted or incompatible".

## Steps to Reproduce

Make backup copy with latest framework version.
Try to open with Realm Browser.

Also: I'm able to open not compressed copy of the DB what was imported into my app from the compressed copy of the DB (so it's not an issues with DB).

## Code Sample

I use code from the Realm guide (section about creation compressed copy of DB for in-bundle usage).

## Version of Realm and Tooling

Realm framework: 0.98.5
Realm browser: 0.97.0 (62)

**Comment by TimOliver** [comment]
Thanks for that @kishikawakatsumi / @victor-kotov-arcadia

There's a new version of Realm Browser that's on the latest version of Realm. It's available here: https://github.com/realm/realm-browser-osx/releases/tag/0.98.5 and the App Store version is currently awaiting review.

Please try that one and see if it helps. There have been some format compatibility breaking changes in the later point releases of Realm 0.98, and this build of the Browser should hopefully take care of them,

Thanks!

**Comment by victor-kotov-arcadia** [comment]
Hi @TimOliver, thanks for pointing to a new version of the Realm Browser, I used it and all goes smoothly, so no issues with newest version of the Browser.

**Comment by TimOliver** [comment]
Awesome! I'm glad to hear that fixed it! Thanks!
