### ISSUE TITLE
Most Common Locations are Greyed Out

### ISSUE THREAD

**Issue by cancan101** [realm/realm-browser-osx#148]
Why are the locations mostly greyed out:? 
![image](https://cloud.githubusercontent.com/assets/51059/14158842/7f5bee80-f6a0-11e5-8c1b-c0ff851b68cb.png)

**Comment by tstanik** [comment]
+1

**Comment by TimOliver** [comment]
Hi guys!

Actually, those ones are always greyed out. The idea there is that those particular menu items are just titles pointing to specific developer locations, and selectable Realm files in those locations appear underneath (i.e., just like Untitled.realm in that picture).

What were you expecting them to do if you clicked on one? While I think the original idea was to be able to open just Realm files from that menu, we could potentially consider making it that clicking on those items would open up their corresponding folder in Finder. :)

**Comment by stel** [comment]
Another suggestion might be to make a submenu for each location and/or hide this items if there are no Realm files found in specific location.

**Comment by tstanik** [comment]
Yes, I was expecting the locations to open in Finder. Also, I don't see any realms under iPhone Simulator, while I can still open them using `Open Realm...` button from the XCode plugin.
