### ISSUE TITLE
'default' could not be opened. It may be encrypted, or it isn't in a compatible file format.

### ISSUE THREAD

**Issue by hiaw** [realm/realm-browser-osx#154]
This seems to happen when the version changed. But I'm using the latest Realm Browser from App Store and latest RealmJS via npm. 

Steps:
1. Create new app for react native
2. Write some data into Realm, can see the size of "default.realm" increase
3. Tries to open with Realm Browser but it gives "'default' could not be opened. It may be encrypted, or it isn't in a compatible file format."

Realm Browser: Version 0.101.0 (72)
Xcode: Version 7.3.1 (7D1014)
OSX: 10.11.4 (15E65)
"realm": "^0.12.0"
"react-native": "^0.25.1"

**Comment by TimOliver** [comment]
Thanks for the issue!

Realm React Native is still using a slightly older version of the file format than the latest version of the Browser, which was updated for Realm Objective-C and Realm Swift.

For the time being, until Realm React Native is also updated, I recommend using one of the older versions of the Browser: https://github.com/realm/realm-browser-osx/releases/tag/0.98.6

**Comment by douglasjunior** [comment]
I have same problem with Realm Android 1.0.0 and Realm Browser 0.98.6. The problems are random.

**Comment by jpsim** [comment]
Realm Java 1.0.0 uses a different version of the Realm file format than Realm Browser 0.98.6. Please use the latest version of Realm Browser (0.103.2 as of this writing).
