### ISSUE TITLE
No compiled version for latest release

### ISSUE THREAD

**Issue by erkro1** [realm/realm-browser-osx#164]
Maybe you're already aware of this but the latest release is missing a compiled version zip, just thought I would let you know.

**Comment by jpsim** [comment]
There are no relevant changes to Realm Objective-C since the latest release of the Realm Browser, so there's no need to make a new release.

**Comment by TimOliver** [comment]
I had a built version already made, so I put one in there for completeness' sake. :)

@stel's done some great work on improving the Browser itself since I cut that release, so I'll cut a new one for 0.103.0 soon too.

**Comment by stel** [comment]
@TimOliver just one thing: could you test it on OS X 10.9 please? Everything should work but I don't have 10.9 installed..
