### ISSUE TITLE
How to update the Realm? (App does not read the database)

### ISSUE THREAD

**Issue by Zuba1703** [realm/realm-browser-osx#168]
Hey. I encountered such a problem. I've updated the Realm browser, today opened a database file, I had a message, offer to update the database file. I clicked "OK" and then my application does not read the file. 
I was told on Twitter- update Realm. But nowhere have I found detailed instructions - how to do it correctly. I have done through the "pod install", but none of that happened.

**Comment by jpsim** [comment]
Which Realm product are you using in your app? Realm Objective-C, Swift, Java, React Native or Xamarin?

The following Realm products are all compatible with the latest version of the Realm Browser (0.103.1):

* Realm Objective-C: 0.101.0 or later
* Realm Swift: 0.101.0 or later
* Realm Java: 0.90.0 or later
* Realm React Native: 0.13.0 or later
* Realm Xamarin: unsupported

**Comment by Zuba1703** [comment]
Realm Swift. 
XCode 7.3
Realm Browser 0.102.1

In the terminal. When I wrote "pod install". There is a message "Using Realm (0.103.1)". But the application does not open the file Realm

**Comment by jpsim** [comment]
Realm Swift 0.103.1 should be compatible with Realm Browser 0.102.1. What's the error you get when opening the file in your application?

**Comment by Zuba1703** [comment]
After the manual filling of the database through the Realm Browser my program crashes with a fatal error.
`fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Unable to open a realm at path '/Users/Zuba/Documents/SwiftLesson/BrainsGame/BaseRealm/TestRealm.realm'" UserInfo={NSFilePath=/Users/Zuba/Documents/SwiftLesson/BrainsGame/BaseRealm/TestRealm.realm, NSLocalizedDescription=Unable to open a realm at path '/Users/Zuba/Documents/SwiftLesson/BrainsGame/BaseRealm/TestRealm.realm', Error Code=2}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-703.0.18.1/src/swift/stdlib/public/core/ErrorType.swift, line 54`

Also, the line 
let uiRealm = try! Realm(path:"/Users/Zuba/Documents/SwiftLesson/BrainsGame/BaseRealm/TestRealm.realm")

gives an error message

Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)".

But database file is contained in a folder on this path

**Comment by jpsim** [comment]
@Zuba1703 can you please share the Realm file that you can't open? That way I can introspect its contents and format to determine why it's failing to open.

**Comment by Zuba1703** [comment]
I recently wrote to tech support address and that's what I was told:

> I confirmed the attached 'TestRealm.realm' was able to be opened.
> 
> I found your project doesn't use CococaPods because the project has pre-built Realm.framework and RealmSwift.framework and they are linked with. So there is Podfile in the project but not used.
> 
> Also, the following code doesn't work the latest version of Realm (0.103.x). Because `Realm(path:)` initializer was removed. You should use `Realm(fileURL:) instead.
> 
> let uiRealm = try! Realm(path: "/Users/Zuba/Documents/SwiftLesson/BrainsGame/BaseRealm/TestRealm.realm")
> 
> So I don't know what happens in your environment actually, but I think something like cache (CocoaPods and Xcode) affects. It may be resolved by cleaning build directory, deleting Derived Data directory and restarting Xcode or your Mac.
> 
> if the above code occurs compilation error, it's correct. The code should be the following in latest version of Realm.
> 
> let uiRealm = try! Realm(fileURL: NSURL(fileURLWithPath: "/Users/Zuba/Documents/SwiftLesson/BrainsGame/BaseRealm/TestRealm.realm"))

**Comment by jpsim** [comment]
Alright, please update us once you've had a chance to try that!

**Comment by TimOliver** [comment]
Hi @Zuba1703! Just following up on this issue; were you able to get it working in the end?

**Comment by stel** [comment]
Closing this for now because of inactivity.
