### ISSUE TITLE
Dates inconsistency

### ISSUE THREAD

**Issue by carotorrehdz** [realm/realm-browser-osx#169]
Hi guys! First of all, thanks for all of your hard work. Realm browser is a really helpful tool. It's just that I'm having some issues with the dates values shown at the browser.

I'm receiving a JSON from my server with dates in UTC timezone 

[![This is part of the json I'm getting from my server.][1]][1]
  [1]: http://i.stack.imgur.com/6j4dL.png

And I call `Realm.createOrUpdateObjectFromJson` to update the realm object and when I open the realm file in the browser, this is how it's getting shown.

[![This is how it's getting save in my realm file.][2]][2]
  [2]: http://i.stack.imgur.com/ZhdCq.png

Does this means that my dates are being saved with UTC timezone, or it's just the browser that's displaying them in my system timezone?

**Comment by jpsim** [comment]
Just like regular `NSDate`s, dates in Realm don't contain any timezone data. So this is the browser rendering a timestamp in your timezone.

**Comment by carotorrehdz** [comment]
Thanks for clarifying this for us.
