### ISSUE TITLE
Compact Realm files

### ISSUE THREAD

**Issue by Allsimon** [realm/realm-browser-osx#177]
Is there a way to compact Realm files using this browser ?

**Comment by TimOliver** [comment]
Hi @Allsimon!

Yep! If you go to 'File > Export To > Compressed Realm...', that'll create a compacted copy of your Realm file. :)

**Comment by stel** [comment]
@Allsimon could we close this issue?

**Comment by Allsimon** [comment]
Sure, I don't know how I could have missed this option: thanks !
