### ISSUE TITLE
Exporting Compacted Realm Failing

### ISSUE THREAD

**Issue by TimOliver** [realm/realm-browser-osx#179]
At present, attempting to export a compressed Realm from the Browser will fail with an error message stating the Realm was accessed from an incorrect thread.

**Comment by webmagnets** [comment]
I see this issue also.

**Comment by numerics** [comment]
I get this every time I go to 'Export to' -> 'Compressed Realm...'
It will ask for a name, go thru the DB... and then report this error... and never creates the new compressed Relm DB.
