### ISSUE TITLE
[Always]Export to CSV crashing

### ISSUE THREAD

**Issue by ankitbabbar89** [realm/realm-browser-osx#180]
While exporting realm file to CSV, it is crashing.Check attached crash dump.
Tried with latest 0.103.2 version too. Same crash.
[realm_crash.txt](https://github.com/realm/realm-browser-osx/files/310904/realm_crash.txt)

**Comment by stel** [comment]
Thanks for reporting this @ankitbabbar89! I was able to reproduce this also, so we will try to fix it.

**Comment by stel** [comment]
Looks like it's a RealmConverter issue, https://github.com/realm/realm-cocoa-converter/issues/12 should fix this.

**Comment by webmagnets** [comment]
I'm having this issue too. Would someone be able to successfully export this for me?

https://www.dropbox.com/s/ku140eg6jcenic2/default%20after%20traditional.realm

Unfortunately this is the only place I have this version of the data.

**Comment by chien** [comment]
We're experiencing the crashes when exporting tables to csv files.

Version: 1.0.2

Crash logs: [https://dl.dropboxusercontent.com/u/18823852/realm_issue/crash_log.txt](url)
Database file: [https://dl.dropboxusercontent.com/u/18823852/realm_issue/1473346446.41202.realm](url)

To reproduce the problem, export "Product" table in the realm file.

**Comment by chien** [comment]
We created a bounty for this issue as a token of appreciation for whoever could fix this issue. 

[https://www.bountysource.com/issues/35094529-always-export-to-csv-crashing](url)

**Comment by webmagnets** [comment]
The link above isn't working. Try this one:
[https://www.bountysource.com/issues/35094529-always-export-to-csv-crashing](https://www.bountysource.com/issues/35094529-always-export-to-csv-crashing)

**Comment by stel** [comment]
@webmagnets, @chien could you please try to build the Browser from `master` branch and check if that bug still exists? Fee to reopen this issue.
