### ISSUE TITLE
Showing 'nil' for String @PrimaryKey

### ISSUE THREAD

**Issue by douglasjunior** [realm/realm-browser-osx#181]
- Realm Browser 0.103.2 (76)
- Android 23 with Realm 1.0.0

I created a small algorithm to generate incremental ID in my apps, but I'm having a problem. My Realm Browser is showing `nil` for a column that is `String` and `@PrimaryKey`.

![captura de tela 2016-06-14 as 11 03 45](https://cloud.githubusercontent.com/assets/1512341/16045690/f5030226-321f-11e6-852b-2648a20292f9.png)

If print the records in Android logcat works fine:
```java
System.out.println("Sequences: " + realm.where(Sequence.class).findAll());
```
Output:
```
I/System.out: Sequences: [Sequence = [{entityName:Produto},{nextId:23}], Sequence = [{entityName:Pedido},{nextId:1}], Sequence = [{entityName:Cliente},{nextId:1}], Sequence = [{entityName:Telefone},{nextId:2}], Sequence = [{entityName:Email},{nextId:2}], Sequence = [{entityName:Endereco},{nextId:2}], Sequence = [{entityName:PedidoItem},{nextId:3}], Sequence = [{entityName:MensagemEmail},{nextId:8}]]
```
My `Sequence.java`:
```java
package my.app.model;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

public class Sequence extends RealmObject implements my.library.Sequence {

    @PrimaryKey
    private String entityName;

    private long nextId;

    @Override
    public String getEntityName() {
        return entityName;
    }

    @Override
    public void setEntityName(String entityName) {
        this.entityName = entityName;
    }

    @Override
    public long getNextId() {
        return nextId;
    }

    @Override
    public void setNextId(long nextId) {
        this.nextId = nextId;
    }
}
```

**Comment by TimOliver** [comment]
Hi @douglasjunior! That's a really strange error. Sorry you're having an issue with the Browser.
Can you please attach that Realm file you've created to this issue so I can try examining it? 
Thanks a lot!

**Comment by douglasjunior** [comment]
The following file. 

https://1drv.ms/u/s!AlSIfFFmI0BJgbdocwh2Fxs2MjJNHA

If I'm not mistaken, I did not have these problems in older versions.

**Comment by TimOliver** [comment]
Thanks a lot for that! Just to make sure that file isn't lost if the link expires, I'll mirror it here too.

[saframaxPedidosMobile.realm.zip](https://github.com/realm/realm-browser-osx/files/321266/saframaxPedidosMobile.realm.zip)

We recently added the ability to display `nil` values in optional property types. It's quite possible this is a specific use case we missed.

**Comment by douglasjunior** [comment]
I'm happy to help. Please, when you have a beta version tell me to test. 😄
