### ISSUE TITLE
Duplicate entries for models without primary key not listed

### ISSUE THREAD

**Issue by jeffjvick** [realm/realm-browser-osx#185]
I have a model without a primary key so it can have multiple rows with the exact same data.  For instance:

Class: Person

Name, Age
John, 15
John, 15
Paul, 11
Paul, 11

However in Realm browser it seems to not display duplicates in the listings for a model.  Like so:
John, 15
Paul, 11

The total count is correct (4 in this case) but it appears the duplicates are removed.  While this may be a connivance feature it is also confusing because there really are multiple rows with the same data but they aren't being shown.  If you select all rows in a normal database it doesn't filter out the duplicates and I don't feel like the browser should either.

This is for realm browser 0.103.1

**Comment by stel** [comment]
Thanks for reporting this issue to us!

This definitely don't look like as a "feature", but unfortunately I wasn't able to reproduce it.

Could you please send us an example Realm file to coproduce this? Thanks!

**Comment by jeffjvick** [comment]
Sure thing, may take a few days to get time to make an example I can share as the realm I saw this on contains personal user data that I can't share.  

It's also possible I'm doing something wrong but either way I would be good to see why I'm seeing this.

**Comment by stel** [comment]
Thanks, @jeffjvick! You can send us your realm file to help@realm.io also.

**Comment by stel** [comment]
@jeffjvick Are you still experiencing this issue? If so, could you please provide an example Realm file or any code sample to reproduce this? Thanks!

**Comment by stel** [comment]
Will close this issue for now as it still isn't reproduced. @jeffjvick please feel free to reopen it if you have a chance to send us more info!
