### ISSUE TITLE
Table header truncated on first view

### ISSUE THREAD

**Issue by astigsen** [realm/realm-browser-osx#189]
![browser_truncated_header](https://cloud.githubusercontent.com/assets/69422/17202743/0431dc0c-5450-11e6-84f1-13f16c715e2e.png)

When the browser first opens a Realm, the header (with the property names and types) is truncated so you can hardly read the type names. It corrects itself as soon as you start using it.

**Comment by stel** [comment]
Doesn't reproduce in the latest version.
