### ISSUE TITLE
Line breaks in string fields

### ISSUE THREAD

**Issue by tonyganch** [realm/realm-browser-osx#199]
Hi,
Thank you a lot for the application.

Is there a way to modify a string field to insert line break (new line)?
I tried typing `\n`, but it is then treated by swift as two characters `\` and `n` and not line break.

Related SO question: http://stackoverflow.com/questions/36388403/realm-how-to-use-line-breaks-in-database-string-entry/36410217

**Comment by bmunkholm** [comment]
Answered in above SO.

**Comment by tonyganch** [comment]
The answer at SO tells you how to store new line from Swift code but not from Realm Browser.
My question is how to insert "\n" as line break from browser application.

Comment from SO which is left unanswered:

> What I had done, and what doesn't work, is to add the "\n" into the text within the RealmBrowser. I was simply testing the layout with some test data and realised I wanted the line breaks, so I went into the Browser to add them. They show up as text rather than line breaks when you do that.

I would like to know how to do that.
Please reopen?

**Comment by tonyganch** [comment]
ping

**Comment by stel** [comment]
@tonyganch sorry for misunderstanding, it seems it's a bug, I'm not even able to insert a newline character from the external text editor
