### ISSUE TITLE
realm browser can set relation?

### ISSUE THREAD

**Issue by soulxenix** [realm/realm-browser-osx#202]
if i define class of realm 
i can set object relation 

ex)class locationcode{
var locationcodeid:string
var locationcodename:string
}

class people
{
var name:String
var location:locationcode  <-- this is linking object
}
but realm browser only import or export data from csv or xlsx? 
if i  insert data to realm file by realm browser
how can i join query?

**Comment by stel** [comment]
@soulxenix are you trying to import some data with relationships from CSV or XLSX? Unfortunately Realm Browser doesn't support that at this time :(

**Comment by sirvon** [comment]
is there currently still no way to model relationships from csv import in realm browser?

**Comment by stel** [comment]
@sirvon no, relationships are not supported when importing from csv.
