### ISSUE TITLE
Realm Browser 2.0.0 Opening Encrypted Realms

### ISSUE THREAD

**Issue by chrisamanse** [realm/realm-browser-osx#204]
1. Open encrypted Realms
2. Expected Results

  After entering key, data should be visible.

3. Actual results

  After entering key, Realm Browser shows no data and models

4. Steps to reproduce

  1. Create encrypted Realm using Realm.Configuration.
  2. Open Realm in Realm Browser, enter key

5. Attached Realm files

  [Realm Types.zip](https://github.com/realm/realm-browser-osx/files/497202/Realm.Types.zip)
  Key for Realm Encrypted (hex): 881af51e5ffc2817b1cb1dc1aec412f0563597f234de206492ee9790a09b28113d7cc6ee0e5746af715c7e19dcc8ef060630bb7f0388e5214d51c25187248d99

6. Versions

  - Realm Browser: 2.0.0
  - RealmSwift: 2.0.0
  - Xcode: 8.0 GM
  - macOS: macOS Sierra 10.12 GM

**Comment by stel** [comment]
Thanks for reporting this issue, @chrisamanse! #206 should fix it.

**Comment by LPFinch** [comment]
@stel can you build new version with fix #206???
I think it's critical bug, older version doesn't work with Realm 2.0.
P.S. Заранее спасибо =)
