### ISSUE TITLE
Cannot see encrypted data in 2.0.0

### ISSUE THREAD

**Issue by jungyang** [realm/realm-browser-osx#207]
I just upgraded Realm browser as well as my app's realm-java to 2.0.0.
After the upgrade, I cannot see anything in the browser if my database is encrypted. I can open the file after entering the key but no table is displayed. I was able to see them in the previous version.
If I don't encrypt the database, then everything is displaying fine.

**Comment by biftekman** [comment]
Same problem here.
Anything new here?

**Comment by stel** [comment]
Sorry for that issue, it's fixed in https://github.com/realm/realm-browser-osx/pull/206 and binaries will be released soon.
