### ISSUE TITLE
Data from CSV/XLSX is always imported as String properties

### ISSUE THREAD

**Issue by stel** [realm/realm-browser-osx#210]
Even if the column in CSV file contains only integers it will be imported as `String` property.

**Comment by PanMluvci** [comment]
+1 for fixing this. I had a hard time with realm browser convert from files .xlsx or .csv to .realm. Now i cannot perform even .max() or operators > < because its string :-/

**Comment by stel** [comment]
`RealmConverter`'s issue https://github.com/realm/realm-cocoa-converter/issues/26

**Comment by stel** [comment]
Fixed in https://github.com/realm/realm-cocoa-converter/issues/26

**Comment by FreudGit** [comment]
2.1.7 = I still have this issue.

**Comment by jpsim** [comment]
@FreudGit exact steps to reproduce? Like sharing a CSV file that triggers this behavior?

**Comment by basememara** [comment]
Below are the steps with the attached XLSX and Realm files produced with Realm Browser `2.1.12`.

1. Open Realm Browser
2. File > Import From > XLSX
3. Choose ImportTest.xlsx file
4. Select destination
5. Open default.realm

`ID` column shows string type but was all integers in source xlsx file (I even tried formatting the columns as numbers).

<img width="819" alt="capturfiles_2" src="https://user-images.githubusercontent.com/892152/29302840-9cc39a04-8155-11e7-8408-633091200065.png">

[ImportTest.xlsx](https://github.com/realm/realm-browser-osx/files/1224178/ImportTest.xlsx)
[default.realm.zip](https://github.com/realm/realm-browser-osx/files/1224179/default.realm.zip)
