### ISSUE TITLE
For list properties, number of records indicator is cut off after 2 digits

### ISSUE THREAD

**Issue by brynjar** [realm/realm-browser-osx#211]
I have a list property, e.g.

`var children: List<TagV2> = List()`

if this list contains > 99 objects, then the count display in the browser app seems to cut off the number after 2 digits, so I can't see how many objects I have.

![screen shot 2016-10-04 at 19 00 56](https://cloud.githubusercontent.com/assets/465908/19084014/fb087b72-8a64-11e6-9a1a-383b08e30adf.png)

**Comment by TimOliver** [comment]
Thanks for the bug report @brynjar! Can you please tell us which version of macOS you're on there?

**Comment by brynjar** [comment]
10.11.6 Browser v.1.0.2
