### ISSUE TITLE
Importing from CSV file gives Int column instead of String with repeated "0" value !

### ISSUE THREAD

**Issue by fadylateef** [realm/realm-browser-osx#226]
After importing .csv database into realm browser and opening the  `default.realm` file 
it gives repeated zero values in `Int` column which is supposed to be `String` column with different text .

<img width="99" alt="screen shot 2016-10-20 at 10 44 44 pm" src="https://cloud.githubusercontent.com/assets/17549441/19577264/d2fbec0e-9716-11e6-8557-9fa152997df8.png">

**Comment by stel** [comment]
@fadylateef thank you for reporting this! Could you please provide an example realm file to reproduce this issue?

There were also made some related fixes in [RealmConverter](https://github.com/realm/realm-cocoa-converter) that is used for importing CSV files, hope it fixes this issue as well.

**Comment by stel** [comment]
Hopefully it's fixed in the latest version of RealmConverter. @fadylateef please feel free to reopen this issue if you have this problem in future versions of Browser.
