### ISSUE TITLE
Realm Browser crashes on open

### ISSUE THREAD

**Issue by jkahn117** [realm/realm-browser-osx#228]
Just started working with Realm and on writing data, wanted to confirm via Realm Browser.  Tried installing via both Homebrew and App Store methods, but always get the following crash:

```
Application Specific Information:
terminating with uncaught exception of type realm::RealmFileException: Unable to open a realm at path '/Users/jkahn/Library/Containers/io.realm.realmbrowser/Data/Library/Application Support/realm-object-server/io.realm.object-server-metadata/sync_metadata.realm': Realm file decryption failed.
abort() called
```

I have tried launching the app by clicking on the .realm file as well as by launching the application directly.

**Comment by jkahn117** [comment]
I was able to correct the issue by:

1. Uninstall Realm Browser
2. Delete `/Users/jkahn/Library/Containers/io.realm.realmbrowser`
3. Install Realm Browser

Was able to open a file, will report back if I run into further issues.

**Comment by cliftonlabrum** [comment]
I find this also occurs if a remote instance of a realm (when using the Realm Object Server) has a different schema than a local one. This can happen if the realm isn't migrated properly.

**Comment by stel** [comment]
Thanks for reporting this issue! What version of Realm Browser and Realm Object Server do you use? Could you also provide a full stack trace or attach a crash log file? It will help us investigate this bug.

**Comment by jkahn117** [comment]
Since taking the corrective action noted below, I have been unable to reproduce the issue (though I did submit the stack track via the Apple Bug Reporter when the application crashed).

Using Realm Browser 2.0.0.
