### ISSUE TITLE
Feature Request: More Robust Realm Listing

### ISSUE THREAD

**Issue by cliftonlabrum** [realm/realm-browser-osx#229]
When you connect to a Realm Object Server, you are presented with a list of recently accessed realms like this:
![image](https://cloud.githubusercontent.com/assets/2513753/19665622/bef74d84-99fa-11e6-8565-f3d9397d8e68.png)

This particular area has huge potential for making the Realm Browser more useful.

While the Realm Browser is a handy development tool, I think it has the potential to be an indispensable app support tool. Here's what I envision:
1. When connecting to an ROS, you should be presented with a table that lists all the users of your app by username and unique ID. This means the listing would scan the ROS for available realms. As it is now, I think the Realm Browser just keeps a "recently viewed" list whether those realms exist on the server or not.
2. This list should be filterable so I can search for a particular ID or username.
3. I could then connect to that user's data to troubleshoot issues they are having.
4. Ideally there would be a way to export their realm file so I could save it locally where the iOS simulator can access it so I can do local development testing using that user's specific data.

This would be incredibly useful, in my opinion. :) Thanks for a great app!

**Comment by stel** [comment]
Thank you very much for this suggestions, @cliftonlabrum!

BTW you should be able to export user's Realms locally for debugging by exporting it as Compacted Realms (File -> Export to -> Compressed Realm...), but unfortunately there is an issue with that right now :( It has already beed fixed in https://github.com/realm/realm-browser-osx/pull/230.

**Comment by stel** [comment]
I believe this issue can be closed now as all these suggestion have been implemented. The only thing here is that all server realms can be filtered by user identity not the user name. In general case users don't have usernames.

**Comment by cliftonlabrum** [comment]
This is fantastic! These changes are most welcome. :) I can't wait to try it.
