### ISSUE TITLE
When opening a ROS-synced realm, can't see new models in schema

### ISSUE THREAD

**Issue by raudabaugh** [realm/realm-browser-osx#234]
Hi,

I have just added a few model classes to my iOS app and they sync perfectly between devices. However, connecting to the Object Server and viewing the realm still displays the old schema.

Is there a way to tell Realm Browser to get the newest schema version?

I'm on Browser 2.0.1 / El Cap 10.11.6. Thank you!

**Comment by raudabaugh** [comment]
Yes, all data entered in the Browser for the old models seems to sync to all devices correctly. I have not seen any errors or warnings in the server log, or the client app log.

**Comment by stel** [comment]
@raudabaugh thank for that info, we'll try to reproduce and fix this issue, for now try to remove `~/Library/Containers/io.realm.realmbrowser` folder (this will reset everything to a default state) and restart Browser.

**Comment by raudabaugh** [comment]
Unfortunately I still don't see the new models after removing that folder.

**Comment by stel** [comment]
We've been finally able to reproduce this issue, it's fixed in #321.
