### ISSUE TITLE
CSV Import: How to specify Boolean? 

### ISSUE THREAD

**Issue by TimothyStulman** [realm/realm-browser-osx#252]
When importing from CSV or Excel, "true" and "false" values are created as String types. How do I specify that they should be Boolean values? 

Thanks!

Tim

**Comment by stel** [comment]
Unfortunately it's not possible right now. I've created https://github.com/realm/realm-cocoa-converter/issues/36 to track this feature.

You can import it as `Int` or `String` property and then convert this property to `bool` manually (e.g. by performing a migration).

**Comment by TimothyStulman** [comment]
Thanks! That's a great idea. I actually ended up using the Cocoapod that reads from CSV to Realm (https://cocoapods.org/?q=realm), but a migration would probably have been easier. I'll do that next time .

**Comment by stel** [comment]
Awesome! I'm closing this issue because it's tracked in https://github.com/realm/realm-cocoa-converter/issues/36 (and almost ready 😉)

**Comment by jderrough** [comment]
Using a sample file from the test suite, boolean fields are not correctly (see screenshot, boolValue is typed as String) imported from CSV despite the fix.

<img width="948" alt="capture d ecran 2017-01-25 a 16 56 50" src="https://cloud.githubusercontent.com/assets/1108358/22298158/ccd8ff7e-e31f-11e6-8a17-a6b49b87e4ae.png">
