### ISSUE TITLE
export to CSV produces nothing

### ISSUE THREAD

**Issue by jarrodparkes** [realm/realm-browser-osx#254]
# Goals

Export data from local Realm to a CSV file.

# Expected results

A CSV file is produced at the directory I choose when selecting "File --> Export To --> CSV".

# Actual results

CSV file is not generated.

# Steps to reproduce

- in the menu go to "File --> Export To --> CSV"
- pick somewhere to save the CSV file (ex: Desktop)
- click "Open" to close the dialog
- ^ after following these steps, CSV file is not produced

# Environment

- Realm Browser 2.1.2
- macOS Sierra 10.12.2

# Other Information

I've been unable to hunt down logs, etc. to try and debug this issue. Is there somewhere I should be looking?

**Comment by bmunkholm** [comment]
It works for me if I open the Realm Browser, click "Tools->Generate Demo Database" and follow your steps. 
Can you replicate that?
What kind of data do you have open in the Realm Browser before you export?

**Comment by jarrodparkes** [comment]
@bmunkholm I'm also able to successfully export to CSV when I do it with the demo database, so I guess it is an issue with my database? how can I debug that (why it isn't exporting)?

I could also try sharing it, but I'm not sure of the best way?

The schema is as follows:

**Game**
title (string), publisher (string), developer (string), coverImagePath (string), owner (<Rating>)

**Platform**
title (string), abbreviation (string), id (string, primary key), games ([Game])

**Rating**
abbreviation (string), shortDescription (string), longDescription (string)

**Comment by bmunkholm** [comment]
The CSV-conversion used by the Browser is also OSS and available here: https://github.com/realm/realm-cocoa-converter, so one option is to simply run that in debug mode on you file to see if there is an error that it barks on and doesn't report back to the Browser.

You can also send your realm file to help@realm.io.

**Comment by jarrodparkes** [comment]
@bmunkholm im having difficulty getting that project to run — it is just a framework, so I'd need to add my own target? like a command-line program or something?

Do you have any advice for getting that project setup?

**Comment by bmunkholm** [comment]
@jarrodparkes Yeah, this project (the browser) includes it. You can see the Readme on how to compile this.

**Comment by jarrodparkes** [comment]
@bmunkholm Got it. So yes, I ran the browser in Debug mode and reproduced the error. It throws and `RLMException` when I try to save the database:

```
2017-01-02 08:43:23.505102 Realm Browser[2213:16903] -[NSVBSavePanel observeValueForKeyPath:ofObject:change:context:] caught non-fatal RLMException 'Realm path must not be empty' with user dictionary {
    RLMRealmCoreVersion = unknown;
    RLMRealmVersion = "2.1.1";
} and backtrace (
	0   CoreFoundation                      0x00007fffb17dce7b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffc63c7cad objc_exception_throw + 48
	2   Realm                               0x00000001005126c1 -[RLMRealmConfiguration setFileURL:] + 225
	3   RealmConverter                      0x0000000100c555f8 _TFC14RealmConverter15CSVDataExporter20exportToFolderAtPathfzSST_ + 328
	4   RealmConverter                      0x0000000100c58cb8 _TToFC14RealmConverter15CSVDataExporter20exportToFolderAtPathfzSST_ + 88
	5   Realm Browser                       0x00000001000186e2 __47-[RLMRealmBrowserWindowController exportToCSV:]_block_invoke_2 + 418
	6   AppSandboxFileAccess                0x000000010015b9ef -[AppSandboxFileAccess requestAccessPermissionsForFileURL:persistPermission:withBlock:] + 975
	7   Realm Browser                       0x00000001000184f4 __47-[RLMRealmBrowserWindowController exportToCSV:]_block_invoke + 276
	8   AppKit                              0x00007fffaf642b0c -[NSVBSavePanel didEndPanelWithReturnCode:] + 68
	9   AppKit                              0x00007fffaf642a70 -[NSVBSavePanel didEndSheet:returnCode:contextInfo:] + 168
	10  AppKit                              0x00007fffaf4f5850 -[NSWindow _endWindowBlockingModalSession:returnCode:] + 308
	11  AppKit                              0x00007fffaf4d6c49 -[NSVBSavePanel observeValueForKeyPath:ofObject:change:context:] + 597
	12  Foundation                          0x00007fffb318871d NSKeyValueNotifyObserver + 350
	13  Foundation                          0x00007fffb3187fb4 NSKeyValueDidChange + 486
	14  Foundation                          0x00007fffb3156e96 -[NSObject(NSKeyValueObserverNotification) didChangeValueForKey:] + 118
	15  ViewBridge                          0x00007fffc4dfa066 __41-[NSViewBridge setObject:forKey:withKVO:]_block_invoke + 447
	16  ViewBridge                          0x00007fffc4e7e52b withHintInProgress + 487
	17  ViewBridge                          0x00007fffc4df9e83 -[NSViewBridge setObject:forKey:withKVO:] + 1014
	18  ViewBridge                          0x00007fffc4df895a -[NSViewBridge nonLocalChangeInProgress:block:] + 390
	19  ViewBridge                          0x00007fffc4e58260 -[NSRemoteViewMarshal exceptionSafeSetRemoteObject:forKey:withReply:] + 256
	20  ViewBridge                          0x00007fffc4e583e8 -[NSRemoteViewMarshal setRemoteObject:forKey:withReply:] + 56
	21  CoreFoundation                      0x00007fffb17503ec __invoking___ + 140
	22  CoreFoundation                      0x00007fffb1750271 -[NSInvocation invoke] + 289
	23  ViewBridge                          0x00007fffc4e7e52b withHintInProgress + 487
	24  ViewBridge                          0x00007fffc4e7e25a __deferNSXPCInvocationOntoMainThread_block_invoke_2 + 233
	25  ViewBridge                          0x00007fffc4dffdf2 +[NSViewServiceApplication withHostPID:invoke:] + 46
	26  ViewBridge                          0x00007fffc4e7e11d __deferNSXPCInvocationOntoMainThread_block_invoke + 179
	27  ViewBridge                          0x00007fffc4e7dd0a __deferBlockOntoMainThread_block_invoke_2 + 544
	28  CoreFoundation                      0x00007fffb17727dc __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	29  CoreFoundation                      0x00007fffb17537e4 __CFRunLoopDoBlocks + 356
	30  CoreFoundation                      0x00007fffb1753326 __CFRunLoopRun + 1878
	31  CoreFoundation                      0x00007fffb1752974 CFRunLoopRunSpecific + 420
	32  HIToolbox                           0x00007fffb0cdeacc RunCurrentEventLoopInMode + 240
	33  HIToolbox                           0x00007fffb0cde901 ReceiveNextEventCommon + 432
	34  HIToolbox                           0x00007fffb0cde736 _BlockUntilNextEventMatchingListInModeWithFilter + 71
	35  AppKit                              0x00007fffaf284ae4 _DPSNextEvent + 1120
	36  AppKit                              0x00007fffaf9ff21f -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2789
	37  AppKit                              0x00007fffaf279465 -[NSApplication run] + 926
	38  AppKit                              0x00007fffaf243d80 NSApplicationMain + 1237
	39  Realm Browser                       0x00000001000230a2 main + 34
	40  libdyld.dylib                       0x00007fffc6cab255 start + 1
)
```

I think it is referring to the Realm `filePath` property. This property was never set during the creation of this Realm, because it was generated with sync configuration. Perhaps that is related to this?

**Comment by bmunkholm** [comment]
Awesome @jarrodparkes. That sounds like a likely root cause! We will get that fixed.
Thanks for reporting, and even troubleshooting!

**Comment by jarrodparkes** [comment]
@bmunkholm no problem! let me know how it goes 👍

**Comment by stel** [comment]
@jarrodparkes while we're fixing this issue you can export synced Realm as Compacted Realm and then export this local Realm to CSV.

**Comment by jarrodparkes** [comment]
@stel sounds good. i was planning for a similar workaround in the meantime 👍
