### ISSUE TITLE
Connection to ROS improvements

### ISSUE THREAD

**Issue by revolter** [realm/realm-browser-osx#261]
I have some questions/feedback about the Realm Object Server connectivity in the Realm Browser app.

1. It would be great if you would be presented with the option to auto connect to a given ROS when you open the app next time(s).
2. Also, from what I saw, if you open a Realm, there's no way for you to go back to the Realms list, and you have to quit and connect again. Or am I missing something?
3. And if it disconnects (e.g. by putting the computer on sleep), there is no way to manually force a reconnect.

**Comment by stel** [comment]
Thank you for your feedback and suggestion @revolter!

Option for automatically reconnect looks like a nice feature, we will keep it in mind for future updates (or feel free to send us a PR ;))

You don't need to quit Realm Browser for getting the list of realm on the Realm Object server, you can open it by File -> Connect to Object Server... menu item.

As for reconnection – Realm Browser should automatically reconnect if the connection was lost, however the can be a delay.

**Comment by revolter** [comment]
> Option for automatically reconnect looks like a nice feature, we will keep it in mind for future updates (or feel free to send us a PR ;))

I might try, but there is the problem of where and how to store the credentials.

> you can open it by File -> Connect to Object Server... menu item.

But this was to create another connection I guess, as it asks me again for my credentials. Wouldn't it be possible not to close the Realms list window and open the Realm window over it?

> As for reconnection – Realm Browser should automatically reconnect if the connection was lost, however the can be a delay.

Could there be a green/red connection status icon somewhere in the interface to know when it's connected or not?

**Comment by stel** [comment]
> but there is the problem of where and how to store the credentials.

If you want to persist credentials between app launches then the best place is keychain. Note that Realm already stores the credentials for valid users (see [docs](https://realm.io/docs/swift/2.2.0/api/Extensions/SyncUser.html#/s:ZvE10RealmSwiftCSo11RLMSyncUser3allGVs10DictionarySSS0__)) so probably it's possible to reuse it in some point.

Keeping the window with realms opened is a good idea, we should definitely consider to support this as well as the connection indication or at least there should be a warning when editing data offline because these changes could potentially be lost if the Browser is closed. Thanks!

**Comment by revolter** [comment]
Reproduced _3._ again, and I waited about 5 minutes but it didn't reconnect.

**Comment by stel** [comment]
I believe #301 and #312 fix 1 and 2 while 3 must have already been fixed in `realm-cocoa`. Closing this issue.

**Comment by revolter** [comment]
When will the new version be available?

**Comment by stel** [comment]
@revolter we will try to release it as soon as possible, right now the only issue that is holding us is https://github.com/realm/realm-browser-osx/issues/297.
