### ISSUE TITLE
Remember Admin Credentials and Token

### ISSUE THREAD

**Issue by cliftonlabrum** [realm/realm-browser-osx#268]
Every time I connect to an object server, I have to re-type my admin's username and password. It's be great if there were a way for the app to remember that info so I could connect more quickly (same thing for the admin token).

Thanks! :)

**Comment by stel** [comment]
Thank you for suggestions @cliftonlabrum! Will try to implement it in future updates or feel free to make a PR ;)

refs https://github.com/realm/realm-browser-osx/issues/261

**Comment by stel** [comment]
Done, thanks @insidegui!

**Comment by cliftonlabrum** [comment]
Thank you! This has been so great! 🙂
