### ISSUE TITLE
How to create multiple models/classes in one realm file from importing multiple csv files?

### ISSUE THREAD

**Issue by sirvon** [realm/realm-browser-osx#273]
When i generate a demo database, I can see 3 model classes are inside the one realm file.

How do I generate one realm file, from importing 3 different csv files.

I would like all 3 csv files' data to be included in the realm file.

So far I am only able to import one csv file into a realm file.

How do I add more models?

**Comment by jpsim** [comment]
Realm Browser's ability to import CSVs is fairly rigid, and mostly exposed as a convenience to get you started with Realm. For more flexibility on how data is imported, I'd recommend you use one of Realm's programmatic interfaces via the [Realm Mobile Database](https://realm.io/products/realm-mobile-database/).

**Comment by stel** [comment]
@sirvon do you need any further help here or can we close this issue?

**Comment by sirvon** [comment]
this can be closed. thank you.
