### ISSUE TITLE
Problem using 'Set linked object'

### ISSUE THREAD

**Issue by DanielAsher** [realm/realm-browser-osx#287]
Hi,

Thanks for a great product!

I have a `RealmBook` class with a `List<RealmPage>`. I would like to be able to add existing `RealmPage` objects to this list, but Realm Browser only lets me add a brand new object.

I noticed #57 but don't know how to use it or whether it is still working.

Any help appreciated!

thanks,
Daniel

**Comment by stel** [comment]
Hi @DanielAsher!

Unfortunately Realm Browser doesn't support adding existing objects to lists currently. #57 implements setting linked object (1-to-1 relationship).

Currently you can try to add your objects manually using Realm sdk.

**Comment by DanielAsher** [comment]
@stel - thanks for the rapid response.
I would love to suggest this as a feature. This is currently a blocking feature in the use of the browser which we would like to allow our content providers to use. One very expensive alternative would be to design a bespoke app to allow replicate the browser with this facility, but that cost is currently prohibitive. I very much hope that you will consider this a feature request.

Is there a workaround I could make to allow this scenario? Perhaps using a `List` of linked objects? Advice much appreciated!

**Comment by stel** [comment]
There is no workaround for this scenario unfortunately. This is definitely a must-have feature, so we will consider adding it and you're always welcome to send us a PR ;)

**Comment by DanielAsher** [comment]
@Step thanks again for clear and rapid response! I'll know not to fiddle around with my schema.

I would love to offer a PR here, but MacOS is outside of my 'code it up in a day' horizon. I do believe this is an essential feature if the browser - the eyes and ears of our realms - is to be useful for content creators.

Best regards,

Daniel

**Comment by stel** [comment]
Implemented in https://github.com/realm/realm-browser-osx/pull/332.
