### ISSUE TITLE
Improve error message when URL is incorrect

### ISSUE THREAD

**Issue by astigsen** [realm/realm-browser-osx#292]
The current error when you try to open a wrong URL (like forgetting to include the port) is really obscure:

<img width="430" alt="screen shot 2017-03-27 at 5 56 46 pm" src="https://cloud.githubusercontent.com/assets/69422/24384214/0a7b5634-1317-11e7-91fe-7e52d6aad4df.png">

**Comment by stel** [comment]
I wasn't able to reproduce this by specifying incorrect url. @astigsen do you have any specific examples when it happens?

![screen shot 2017-03-29 at 10 51 24 am](https://cloud.githubusercontent.com/assets/429275/24446428/aeeeef3a-146d-11e7-8a17-8a1e358f5c31.png)

![screen shot 2017-03-29 at 10 53 17 am](https://cloud.githubusercontent.com/assets/429275/24446497/f25b3e4a-146d-11e7-8e7a-d9a141feb8e9.png)

**Comment by stel** [comment]
https://github.com/realm/realm-browser-osx/pull/329 introduces some UI improvements to handle URLs better.
