### ISSUE TITLE
Is this proper place to signal that we have v2.5.0 version of realm-cocoa but not compatible browser?

### ISSUE THREAD

**Issue by pbrewczynski** [realm/realm-browser-osx#293]
Is this place proper to signal that we have v2.5.0 version of realm-cocoa but not compatible browser?

:(

**Comment by stel** [comment]
Yes, we're working on that in https://github.com/realm/realm-browser-osx/pull/294 and the update will be released soon.

**Comment by stel** [comment]
@pbrewczynski you can download the latest version at https://github.com/realm/realm-browser-osx/releases/tag/v2.1.7. The update on the Mac App Store will be available after Apple Review.

**Comment by pbrewczynski** [comment]
Thank you.
