### ISSUE TITLE
Can't connect to server 

### ISSUE THREAD

**Issue by switchawk** [realm/realm-browser-osx#295]
Hi,

Since I updated to 2.1.7 (91) I can't seem to connect to my server. Connecting from the web browser works fine. I also connect using the browser earlier, so I'm pretty sure it's something in the update.
```
Failed to connect to Object Server.
Check the URL and that the server is accessible.
```

**Comment by stel** [comment]
@switchawk please note (from [Realm 2.5.0 Release Notes](https://github.com/realm/realm-cocoa/releases/tag/v2.5.0)):

> If using synchronized Realms, the Realm Object Server must be running version
1.3.0 or later.

Make sure you use the latest version of Realm Object Server.

**Comment by switchawk** [comment]
Noob question: How do I update the server? the docs only specify how to install.

**Comment by adellhk** [comment]
@stel Do you have any instructions on updating our Realm Object Server version? This may not apply to everyone, but I'm using AWS EC2.

**Comment by stel** [comment]
Happy to hear that your server is up to date now, @adellhk! As you mentioned, you can find instructions for updating and lot of other useful info in [our docs](https://realm.io/docs/) ;)
