### ISSUE TITLE
Wont open files generated from latest realm/js

### ISSUE THREAD

**Issue by wilomgfx** [realm/realm-browser-osx#299]
I cant open .realm dbs if they are generated from https://github.com/realm/realm-js

It says i have to upgrade the files to the latest version.  Also doesnt allow me to view the realm db when my emulator is using it.

Rolling back to realm-browser-osx **2.6.1** fixes the wrong realm file version.
**Yes my emulator is 64 bit (iphone 6)**

**Running macos 10.12.4**

**Comment by jpsim** [comment]
Realm Browser 2.1.7 reads and writes files in a new format, which Realm JS doesn't yet support. Once a version of Realm JS with realm/realm-js#949 is released, you'll be able to access your Realm files simultaneously with both your emulator and Realm Browser 2.1.7.

**Comment by wilomgfx** [comment]
Thats what i thought. Thanks :)!
