### ISSUE TITLE
App store doesn't show updates for app

### ISSUE THREAD

**Issue by noelmansour** [realm/realm-browser-osx#300]
I was on Realm Browser 2.1.5. When I checked the App store for updates, it didn't indicate that one was available. However, I could see in the release notes, that 2.1.7 was the latest.

In order to get it, I had to delete the old one and reinstall from scratch. I wonder if it installed the update but didn't replace the old one?

**Comment by jpsim** [comment]
Actually 2.1.7 is available on the Mac App Store here: https://itunes.apple.com/app/realm-browser/id1007457278

![image](https://cloud.githubusercontent.com/assets/474794/24880010/939c4ba4-1ded-11e7-9ae6-e36afff3f331.png)

**Comment by nicholas-jomo** [comment]
I also see the update when I open the AppStore app on my Mac OS Sierra.

**Comment by noelmansour** [comment]
I think I was unclear in my description.

It's not that v2.1.7 was unavailable, but that when I checked, it didn't show the "Update" option. Instead, it just showed the "Open" option that appears when you're on the latest version.

Unfortunately, I didn't check to see if there were multiple versions of the Realm Browser installed on my machine. Perhaps that was the case and I was just using a residual older version without realizing.

I hope that clarifies it. Also, I'm running OS X 10.11.6.

**Comment by nicholas-jomo** [comment]
Well, it's an OS X issue, isn't it?

**Comment by jpsim** [comment]
Have you filed a Radar? You can do so here, if you have an Apple Developer ID: https://bugreport.apple.com

This is an issue that's entirely out of our control and in Apple's hands.
