### ISSUE TITLE
Change temp files folder

### ISSUE THREAD

**Issue by mgohin** [realm/realm-browser-osx#304]
Hi,

I first choose a directory for temp files after first launch, but I would like to change it now, it spam the directory :(

![image](https://cloud.githubusercontent.com/assets/3430304/25024464/54fa002c-209e-11e7-8d2f-020ca5258e0e.png)

**Comment by stel** [comment]
@mgohin could you please clarify what do you mean by temp files folder? Where did you choose it?

**Comment by mgohin** [comment]
First time I launched Realm Browser, I think it asked me a folder to use to create those .lock and .management files, right ? Or I mixed up with another software ?
Are those file always created in the same folder as the .realm opened file ?

**Comment by stel** [comment]
These files are generated by Realm automatically in the same folder each time you open realm file, please learn more about auxiliary files in docs at https://realm.io/docs/swift/latest/#auxiliary-realm-files.

**Comment by mgohin** [comment]
Ok, so is it possible to automatically delete those files when closing Realm Browser ?

**Comment by stel** [comment]
Other processes can open the same realm file at the same time, so it's not a good idea to delete those files automatically.

**Comment by mgohin** [comment]
Ok, it's not very convenient when dropping the realm file in a crowded folder

**Comment by stel** [comment]
These files are required by Realm internally and usually are hidden from the user in app's specific directories.

I'm closing this issue because it's not related to the Realm Browser itself, but your welcome to open another one in https://github.com/realm/realm-core and feel free to ask us any other questions!

**Comment by mgohin** [comment]
Ok. I opened an issue to try ;)

https://github.com/realm/realm-core/issues/2576
