### ISSUE TITLE
Request for A Linux Version Browser 

### ISSUE THREAD

**Issue by Leo428** [realm/realm-browser-osx#307]
Hi, dear developers! 
Recently I am using the realm server on Ubuntu and I found it very cool and useful. I also tried out the mac version realm browser on other's mac. I wish I could have a mac but currently I only have windows and Ubuntu on my devices. So I am asking if it is possible for you guys to develop a Linux version of the browser. It would be very helpful if we have this option supported by the official. Thank you!

**Comment by songhaonangit** [comment]
Hi, 
I wish I could have a mac but currently I only have windows and Ubuntu on my devices. So I am asking if it is possible for you guys to develop a windows  or ubuntu version of the browser.

**Comment by songhaonangit** [comment]
You use the Realm Studio with linux .

**Comment by sytolk** [comment]
Or [stetho-realm](https://github.com/uPhyca/stetho-realm) for Android

**Comment by bdash** [comment]
This now exists as [Realm Studio](https://realm.io/products/realm-studio/).
