### ISSUE TITLE
C# Generator creates lists for to-one relationships

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-browser-osx#308]
Generating the demo database and exporting C# definitions from it creates this:
```csharp
public class RealmTestClass2 : RealmObject
{
    public long integerValue { get; set; }

    public bool boolValue { get; set; }

    public IList<RealmTestClass1> objectReference { get; }
}
```

The last property should be
```
    public RealmTestClass1 objectReference { get; set; }
```

**Comment by jpsim** [comment]
A quick look at the implementation seems to show this isn't possible 🤔 

https://github.com/realm/realm-browser-osx/blob/v2.1.7/RealmBrowser/Support/RLMModelExporter.m#L610-L682

**Comment by kristiandupont** [comment]
To me it looks like a missing `break` statement here https://github.com/realm/realm-browser-osx/blob/v2.1.7/RealmBrowser/Support/RLMModelExporter.m#L668

**Comment by jpsim** [comment]
You're right!
