### ISSUE TITLE
Crash when trying to connect to a *restarted* Azure VM

### ISSUE THREAD

**Issue by ajonno** [realm/realm-browser-osx#316]
Created an Azure Realm deployment. The Azure IP address / Realm sync test app (React Native) worked nicely and I could browse data using Realm Browser.

Shut down Azure VM.

Restart Azure VM.

Update the RN app to use new Azure IP address. Use new IP address in Realm Browser.

Every single open of Realm Browser crashes.

I downloaded and built from source in XCode. Here is the crash error:

![image](https://cloud.githubusercontent.com/assets/3005269/26023943/ac967ac6-380a-11e7-8eaa-c843ae6bfbb3.png)

**Comment by stel** [comment]
As a temporary workaround please delete the directory `~/Library/Containers/io.realm.realmbrowser` and restart the Browser.

This issue is tracked in https://github.com/realm/realm-object-store/issues/296 and once it's resolved it will be available for the Browser as well.

**Comment by ajonno** [comment]
Thanks. Tried the workaround but Realm Browser still crashes.

**Comment by stel** [comment]
@ajonno according to the screenshot the Browser doesn't crash but can't open a specified realm url. Please check the url and credentials and make sure specified realm exists on the server.
