### ISSUE TITLE
Primary key always interrupted as GUID??

### ISSUE THREAD

**Issue by Craig-K2** [realm/realm-browser-osx#320]
Having installed the browser v2.1.8(92) on my Mac osSierra and opened my very empty realm to add some objects, noticed a discrepancy between the model class and how the browser displays the primary key field. See screen grabs...

<img width="777" alt="screen shot 2017-05-29 at 13 18 57" src="https://cloud.githubusercontent.com/assets/29040990/26549745/5b7ce35e-4472-11e7-9c7a-208a848aab82.png">

![screen shot 2017-05-29 at 13 19 39](https://cloud.githubusercontent.com/assets/29040990/26549754/6ad1cca2-4472-11e7-9f35-9fda7878bc1c.png)

The Name field is set to the primary key for uniqueness and will be input. The Id field will be used as the look up value.

Thanks

**Comment by stel** [comment]
Thanks for reporting this, @Craig-K2! Could you send us a realm file to reproduce this issue?

**Comment by Craig-K2** [comment]
Hi Dmitry,

Sorry for not replying earlier, been on a short holiday. I would gladly
upload the realm file for you but I'm kind of new to GitHub and do not want
the public to have access to it.  I created a zip file and dragged it onto
GitHub - the url created was available to the public.

How should I do this?

**Comment by jpsim** [comment]
@Craig-K2 thanks for being open to working with us 😄 . You can email anything privately to us at help@realm.io. Make sure to include a link to this issue so we know what it's in reference to. Thanks!

**Comment by stel** [comment]
@Craig-K2 I've checked the realm file you sent us and to me everything looks good – realm schema matches the schema definition you posted. However if the main concern was related to the default property value, I'm not sure if Realm Xamarin support that. I suggest to ask this question in https://github.com/realm/realm-dotnet.

**Comment by stel** [comment]
I'm closing this issue for now. @Craig-K2 if you need any further help or have any details to share please feel free to reopen it or create a new one.
