### ISSUE TITLE
Realm Browser Log In Failing

### ISSUE THREAD

**Issue by jdluker** [realm/realm-browser-osx#323]
### 1. Goal
Log in to a ROS via the Realm Browser.

### 2. Expected Results
Successfully log in to a ROS via the Realm Browser.

### 3. Actual Results
<img width="645" alt="screen shot 2017-06-02 at 7 17 19 am" src="https://cloud.githubusercontent.com/assets/8332971/26731790/cd93a080-477a-11e7-919d-9205c9d10e11.png">

### 4. Steps to reproduce
I am attempting to connect to the following URL using a username and password:
(ask me for the URL)
I am able to log in to the ROS via Chrome. I am listed as an admin user for this ROS.

### 6. Versions
Realm Browser: 2.1.8
ROS: 1.7.5

@ianpward

**Comment by stel** [comment]
According to the error message ROS is not accessible on specified URL and port number, please make sure your specified it correctly.

**Comment by ianpward** [comment]
@jdluker can you try a `netstat` on that server and ensure it is listening on that port and IP?

**Comment by jdluker** [comment]
@stel Sorry for the unresponsiveness. I have been on vacation.

One side note... this ROS has whitelisted IP's, which is probably why you do not get a response. I can access it via my Chrome browser with the URL provided above. But I cannot access it via the Realm Browser. I'm sure this will make it way more difficult for us to debug!

I performed a `netstat` on the server. Here is the result:

[netstat_results.txt](https://github.com/realm/realm-browser-osx/files/1068611/netstat_results.txt)

Let me know what else I can do to help!

**Comment by ianpward** [comment]
@jdluker Are you going some sort of proxy/firewall to get to the ROS?

**Comment by jdluker** [comment]
@ianpward I am not, unless I am working remotely. If I am working remotely, then I VPN into our Solstice network. Otherwise, I am just using our office network.

**Comment by jdluker** [comment]
I think maybe Elliot Butler could help us understand how the ROS is set up and how the whitelisting is configured.

**Comment by stel** [comment]
@jdluker I believe we've identified an issue on a server side so I'm closing this issue. Please feel free to reopen it or create a new one if you need any further help.
