### ISSUE TITLE
Import from CSV does not work

### ISSUE THREAD

**Issue by softwarejoint** [realm/realm-browser-osx#334]
Realm Browser crashes when importing any format any size of data. 

Browser version Version 2.1.10 (94) latest from appstore

Attached a simple csv file.
[csvfiledata.txt](https://github.com/realm/realm-browser-osx/files/1126369/csvfiledata.txt)

Incident Identifier: 7B066A65-2A4C-4650-AB82-BAD8F7B5341A
CrashReporter Key:   AE544290-F20C-5908-B516-A22C64A3CA2F
Hardware Model:      MacBookAir7,2
Process:         Realm Browser [3959]
Path:            
Identifier:      io.realm.realmbrowser
Version:         2.1.10 (94)
Code Type:       X86-64
Parent Process:  launchd [1]

Date/Time:       2017-07-05T23:56:16Z
Launch Time:     2017-07-05T23:54:32Z
OS Version:      Mac OS X 10.12.5 (16F73)
Report Version:  104

Exception Type:  SIGABRT
Exception Codes: #0 at 0x7fffd418ad42
Crashed Thread:  0

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RLM:Unmanaged csvfiledata count]: unrecognized selector sent to instance 0x6080002abee0'

Last Exception Backtrace:
0   CoreFoundation                       0x00007fffbe96c2b3 __exceptionPreprocess + 147
1   libobjc.A.dylib                      0x00007fffd377748d objc_exception_throw + 48
2   CoreFoundation                       0x00007fffbe9edf04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
3   CoreFoundation                       0x00007fffbe8de755 ___forwarding___ + 1061
4   CoreFoundation                       0x00007fffbe8de2a8 _CF_forwarding_prep_0 + 120
5   Realm                                0x0000000105a15050 0x1059da000 + 241744
6   Realm                                0x0000000105a16584 0x1059da000 + 247172
7   Realm                                0x0000000105a35cf8 0x1059da000 + 376056
8   Realm                                0x0000000105a3579f 0x1059da000 + 374687
9   RealmConverter                       0x00000001060a4b5e 0x10609d000 + 31582
10  RealmConverter                       0x00000001060a3f6e 0x10609d000 + 28526
11  Realm Browser                        0x0000000105800061 0x1057d8000 + 163937
12  AppSandboxFileAccess                 0x000000010583e138 0x10583c000 + 8504
13  Realm Browser                        0x00000001057ffef1 0x1057d8000 + 163569
14  libsystem_trace.dylib                0x00007fffd428e3a7 _os_activity_initiate_impl + 53
15  AppKit                               0x00007fffbcb5a721 -[NSApplication(NSResponder) sendAction:to:from:] + 456
16  AppKit                               0x00007fffbc62d666 -[NSMenuItem _corePerformAction] + 324
17  AppKit                               0x00007fffbc62d3d2 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
18  libsystem_trace.dylib                0x00007fffd428e3a7 _os_activity_initiate_impl + 53
19  AppKit                               0x00007fffbc6b6955 -[NSMenu performActionForItemAtIndex:] + 121
20  AppKit                               0x00007fffbc6b68cc -[NSMenu _internalPerformActionForItemAtIndex:] + 94
21  AppKit                               0x00007fffbc6b66f9 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 107
22  AppKit                               0x00007fffbc56d580 NSSLMMenuEventHandler + 986
23  HIToolbox                            0x00007fffbde1bd85 _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1708
24  HIToolbox                            0x00007fffbde1aff6 _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 428
25  HIToolbox                            0x00007fffbde30d14 SendEventToEventTarget + 40
26  HIToolbox                            0x00007fffbde7d3e6 _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 411
27  HIToolbox                            0x00007fffbdea89fb SendMenuCommandWithContextAndModifiers + 59
28  HIToolbox                            0x00007fffbdea89aa SendMenuItemSelectedEvent + 188
29  HIToolbox                            0x00007fffbdea887d _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 96
30  HIToolbox                            0x00007fffbdea92b7 _ZL14MenuSelectCoreP8MenuData5PointdjPP13OpaqueMenuRefPt + 702
31  HIToolbox                            0x00007fffbdea8f66 _HandleMenuSelection2 + 460
32  AppKit                               0x00007fffbc55d368 _NSHandleCarbonMenuEvent + 239
33  AppKit                               0x00007fffbc7d7702 _DPSEventHandledByCarbon + 54
34  AppKit                               0x00007fffbcb580c5 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 963
35  AppKit                               0x00007fffbc3d13db -[NSApplication run] + 926
36  AppKit                               0x00007fffbc39be0e NSApplicationMain + 1237
37  libdyld.dylib                        0x00007fffd405c235 start + 1

**Comment by patreu22** [comment]
+1

**Comment by stel** [comment]
Thanks for reporting this issue!

**Comment by stel** [comment]
This issue is now tracked in https://github.com/realm/realm-cocoa-converter/pull/47.

/cc @bdash
