### ISSUE TITLE
LinkingObjects column shows zero count

### ISSUE THREAD

**Issue by dmorrow** [realm/realm-browser-osx#337]
Objects with a LinkingObjects relationship don't show a correct count.  All relationships show zero and clicking the link shows an empty list.
Querying the relationship in code shows the correct count.

Realm Browser 2.1.10 (94)
Mac OS X 10.11.6

**Comment by jpsim** [comment]
`LinkingObjects` aren't persisted in the Realm file, they're just views into the underlying data, meaning that the browser isn't aware of them. So those "inverse relationship" properties won't even display as columns in the browser.

**Comment by dmorrow** [comment]
I'm sorry - I was looking at an older version of the Realm where I was manually managing these values.
