### ISSUE TITLE
Possibility to open realm file through ssh?

### ISSUE THREAD

**Issue by MihaelIsaev** [realm/realm-browser-osx#346]
Hello guys,

Could you please implement a possibility to open a realm file stored on server through ssh connection?
I just use realm as a database on my web server and there is no possibility to watch what's going on in the realm database in real time.. I can only copy the database to my computer and then open it... it's a little bit not convenient..

**Comment by stel** [comment]
Thanks for this idea, @MihaelIsaev but I don't think it's something that we can implement inside the Browser. I'd rather suggest you to take a look on [Realm Mobile Platform](https://realm.io/products/realm-mobile-platform/) and the way you can sync Realms across devices.
