### ISSUE TITLE
Realm Browser 3.0.0-beta Browser 

### ISSUE THREAD

**Issue by sunilshettyy** [realm/realm-browser-osx#347]
Open old .relam file -  it will ask to upgrade, Then run the app - it will crash(every time),
Just installed older browser again now app works as expected,

**Comment by stel** [comment]
Thanks for reporting this issue, @sunilshettyy!

Please try to use [Beta 2](https://github.com/realm/realm-browser-osx/releases/tag/v3.0.0-beta.2). If the problem still there, could you please provide us a crash report or an example realm file to reproduce this issue?

**Comment by stel** [comment]
I'm closing this for now because of inactivity. @sunilshettyy please feel free to reopen this issue or create a new one.
