### ISSUE TITLE
Index .realm files found in common developer folders

### ISSUE THREAD

**Issue by TimOliver** [realm/realm-browser-osx#35]
To make it easier for developers to locate .realm files generated by Simulator builds, a basic indexing feature to aggregate all of the apps using Realm inside the simulator should be added.

**Comment by TimOliver** [comment]
I was thinking about this one a bit today, trying to figure out how to lay it out in a way that's considered natural on OS X.

Looking at Sketch, Xcode and a few other apps, it looks like standard convention is to display this sort of 'quick launch' behavior in a dialog that appears when the app is launched.

Here's a really quick mockup of a potential launch screen layout:

![realmbrowserwecomescreen](https://cloud.githubusercontent.com/assets/429119/8990116/dbdee3ee-3722-11e5-8b8c-4d4480e6997d.jpg)

What would be the general quorum on this?

/cc @timanglade @jpsim @yoshyosh @mrh-is

**Comment by yoshyosh** [comment]
I like that, I think we should make it as easy as possible to find your current Realm file that you are debugging. I had some ideas like this:

![screen shot 2015-07-30 at 10 48 26 am](https://cloud.githubusercontent.com/assets/775056/8990652/9b361756-36a8-11e5-8d5f-9410311ebf0b.png)

**Comment by timanglade** [comment]
I like it but we also need to cover the “empty” case where there are no
recently opened Realm files, or no Realm files in “common developer
folders”.

**Comment by mrh-is** [comment]
Good for me, with a couple caveats:

- Definitely need a "Show this when Realm Browser opens" checkbox so I can make this stop happening
- Make sure we don't do this if we're reopening a file (such as OS X window restoration)
- I like Joe's, it's pretty. Would make the buttons a bit larger, and remove ß

**Comment by timanglade** [comment]
I was actually more of a fan of Tim’s: looks more like standard Mac OS UI
(minus the buttons in the upper right corner, which I believe look off for
whatever reason). I agree Joe’s is prettier but I think it’s too branded
and not Mac-ish enough.
