### ISSUE TITLE
Realm Browser 3.0.0-beta.2 Prompts for Encryption Key

### ISSUE THREAD

**Issue by cliftonlabrum** [realm/realm-browser-osx#352]
When I try to open a realm file that was created by the Realm Object Server using `3.0.0-beta.2` of the Realm Browser, I get an error:

> Please enter a valid encryption key for this Realm file.

I'm not deliberately using any encryption in my app. Is this error an automatic consequence of trying to open a Realm used with the ROS? Is this encryption key available somewhere on my ROS?

<img width="1089" alt="rb-enc" src="https://user-images.githubusercontent.com/2513753/29956883-f79f8f68-8e9e-11e7-9341-846eee58edc4.png">

**Comment by bmunkholm** [comment]
@cliftonlabrum Sorry about missing this one. Yeah that's likely due to incompatibility with the beta version of ROS and the Browser. We will update and release a new version soon.

**Comment by esutton** [comment]
See https://github.com/realm/realm-browser-osx/issues/359
