### ISSUE TITLE
Is there a way to update/refresh the Realm Browser when data is changed besides downloading the container from device each time?

### ISSUE THREAD

**Issue by brittanygraft** [realm/realm-browser-osx#354]

**Comment by bmunkholm** [comment]
@brittanygraft If you are using RMP with syncronized Realms, then they are updated in real time. If you are using a simulator to run your app, then you can also just open the Realm the iOS simulator is using and you will see realtime updates. If you are doing Android developement, you have to download the Realm before you can see it. Alternatively you can use one of the 3'rd party device browsers for Realm directly on your phone.
