### ISSUE TITLE
Run unit tests in CI

### ISSUE THREAD

**Issue by jpsim** [realm/realm-browser-osx#36]
Travis only *builds* the browser, but it should really be running the unit tests to confirm that everything still works. The current CI script is `xctool -workspace RealmBrowser.xcworkspace -scheme RealmBrowser build  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO`.

**Comment by TimOliver** [comment]
Ah, thanks for that! I've updated the CI script and Xcode schema to run the tests now.
