### ISSUE TITLE
Crash when trying to delete a record

### ISSUE THREAD

**Issue by mrvincenzo** [realm/realm-browser-osx#363]
Version 3.0.0

Worked well on beta2.

**Comment by mrvincenzo** [comment]
Any updates?

**Comment by bmunkholm** [comment]
That's easily reproduced. Thanks for reporting! WE should get that fixed.
As a workaround, did you try [Realm Studio](https://realm.io/products/realm-studio/)? It's the new cross platform replacement for the Realm Browser.

**Comment by mrvincenzo** [comment]
Thanks @bmunkholm. I will check it out.
