### ISSUE TITLE
Please enter a valid encryption key for this Realm file

### ISSUE THREAD

**Issue by rahulmenezes** [realm/realm-browser-osx#371]
I get the following message when trying to open a realm file: "Please enter a valid encryption key for this Realm file".

Last time I saw this, I solved the issue by upgrading to the latest Realm Browser version but I am already on the latest version this time.

Realm Browser: 3.0.1
Realm version 4.1.0

**Comment by bmunkholm** [comment]
Can you open it fine from the app? Then the file is ok, and it certainly sounds like a mismatched version. If you can't open the file from your app, then it's likely corrupted.

**Comment by rahulmenezes** [comment]
This is a customer's realm file. He is able to use the app fine, however when he sends feedback(which has the realm file in it) we cannot open it in realm browser. When I import his realm into my emulator and try to open it, I get a "Bad File Header(#1)" error.

**Comment by bmunkholm** [comment]
@rahulmenezes And I assume you are not using encryption?
Is it just one user? It could then be corrupt.

**Comment by rahulmenezes** [comment]
We are using encryption. We just had another user have this issue too. I wonder if it has something to do with the compactOnLaunch() parameter we recently added.

**Comment by bmunkholm** [comment]
Well if it is encrypted, you need to enter the encryption key to open it in the browser.

**Comment by rahulmenezes** [comment]
Yes and when I do enter the key I get this message: ""Please enter a valid encryption key for this Realm file".

**Comment by bdash** [comment]
What format are you entering the encryption key in? I believe the browser expects the hex representation of the key to be entered.

**Comment by rahulmenezes** [comment]
Yes, I am entering the 128-character string of the hex password.

**Comment by bmunkholm** [comment]
@rahulmenezes Can you please validate that you can create another encrypted file with the key, and open it with the browser? If you can then at least we know that you enter the key correctly, and then it seems like the file may be corrupted.

**Comment by bmunkholm** [comment]
closing this for now. Let me know if you continue to have trouble.

**Comment by ivnsch** [comment]
Where do I find the encryption key (not setting any in my code)? Using Realm Browser 3.0.1 and RealmSwift 3.7.5
