### ISSUE TITLE
allow can't clicked by iFunbox  Could not open .realm

### ISSUE THREAD

**Issue by idewindy** [realm/realm-browser-osx#374]
Mac:10.13
realm-browser: 3.0.1
realm-cocoa:2.9.1
![5cf88b73-2656-4118-a5a6-2dbd8bf2f7cb](https://user-images.githubusercontent.com/22510807/37381013-0c7da058-2776-11e8-8a41-acd30214be9c.png)

**Comment by bmunkholm** [comment]
@idewindy The application you are showing does not have anything to do with Realm. The browser can't open the file unless it can get access to the file. So there is nothing that can be changed in the Browser to fix your issue. You need to fix that with iFunBox or move the file to a location the Browser has access to.
