### ISSUE TITLE
Realm Studio is bad. You should definitely keep maintaining this

### ISSUE THREAD

**Issue by allenhumphreys** [realm/realm-browser-osx#376]

**Comment by bmunkholm** [comment]
@allenhumphreys Could you please make constructive comments about what should be improved in Studio where the Browser is better?
Thanks!

**Comment by bmunkholm** [comment]
@allenhumphreys We actually really appreciate your feedback - but it's not really actionable without further input.

**Comment by allenhumphreys** [comment]
Thanks @bmunkholm, I’ll elaborate when I have a minute.

**Comment by allenhumphreys** [comment]
I'm not gonna elaborate, because I'm busy, suffice it to say, I'm still using the native app because it just works better.
