### ISSUE TITLE
Add support for launching app with argv

### ISSUE THREAD

**Issue by jhanzo** [realm/realm-browser-osx#379]
In order to launch app easily, it could be very interesting to have argv available in app.

In this way, app would be opened in CLI with : 
```
open -a "Realm Browser" --args "REALM_PATH/db.realm"
```

**Comment by bmunkholm** [comment]
@jhanzo That would be great. But as written in the Readme, we have deprecated this application as we now have a cross-platform alternative [realm-studio](https://realm.io/products/realm-studio). Have you seen that? Do you have reasons not to use that?

**Comment by jhanzo** [comment]
@bmunkholm yes indeed I already saw this feedback but for now I am not using it and I don't find enough documentation for migrating. AFAIK Realm Studio is not open source and feature request proposals are not possible on this new tool.

**Comment by bmunkholm** [comment]
@jhanzo it is actually open source - so you can make all the PR's you like :-) See https://github.com/realm/realm-studio/

What kind of documentation are you looking for? There is no "migration" to do.

**Comment by jhanzo** [comment]
Ok right, i was completely mistaken 😅So I would create the same FR on the other projet... Let me have a look on it before 😁. Maybe I have missed something because I learn this tool was deprecated by going to this repo.
