### ISSUE TITLE
Set/modify relations between objects

### ISSUE THREAD

**Issue by TimOliver** [realm/realm-browser-osx#45]
When creating or modifying objects that contain RLMObject or RLMArray properties, it would be possible to set (and in the case of RLMArray, reorder) the sub-objects that these properties are referencing.

This may require a new UI dialog to be designed.

**Comment by ReDetection** [comment]
Seems like title is only about set/modify relation (which is done), but description tells that reordering left to do. Quite confusing, can you please fix it?

**Comment by DanielAsher** [comment]
This would be awesome!

**Comment by stel** [comment]
Implemented in https://github.com/realm/realm-browser-osx/pull/332.
