### ISSUE TITLE
Realm file format icon

### ISSUE THREAD

**Issue by TimOliver** [realm/realm-browser-osx#48]
Create a new icon file in the same design vein as Apple's document formats to be used for .realm files that have been associated with be opened in Realm Browser.

**Comment by TimOliver** [comment]
Looking at a lot of other apps, it seems the general convention for file format icons on OS X is to use the generic system documents icon, and compose the app's icon on top of it.

<img width="256" alt="realmfileformaticon" src="https://cloud.githubusercontent.com/assets/429119/8977586/0a0b1112-36cd-11e5-9374-738ceadc73f4.png">

Any objections or alternative suggestions? :)
/cc @yoshyosh @mrh-is @timanglade

**Comment by timanglade** [comment]
lgtm. Maybe make the icon’s shadow a tinge darker than normal (especially
in the upper left “corner”) so the white border doesn’t blend too much into
the sheet of paper behind it?

**Comment by TimOliver** [comment]
Excellent! Glad you like it!

No worries. I'll have a play with it to make sure it doesn't look like that when it's presented in a white Finder window.

**Comment by mrh-is** [comment]
Is the page curl still there in Yosemite? The iWork document icons don't have it.

Other than that LGTM.

**Comment by TimOliver** [comment]
@mrh-is Yep! It looks like the iWork apps might be a bit of an exception to the rule, but the majority of system file formats still use that style:

![screen shot 2015-08-01 at 1 41 33 am](https://cloud.githubusercontent.com/assets/429119/9013469/c45a7fa4-37ee-11e5-9f53-9e52434a01f9.png)

Cool! I'm putting together a pull-request with the new icon integration now.
