### ISSUE TITLE
Realm Browser crashing with Realm v0.94.0

### ISSUE THREAD

**Issue by lionpants** [realm/realm-browser-osx#52]
The Realm Browser was working perfectly before Realm v0.94.0, but since updating (we moved to cocoapods too); the browser now crashes if it is open while a change to the Realm Database is made in the running Simulator. I am using the new version of the Browser from the AppStore.

I'm able to reproduce this 100% of the time. Here's the crash info...

    Process:               Realm Browser [78299]
    Path:                  /Applications/Realm Browser.app/Contents/MacOS/Realm Browser
    Identifier:            io.realm.realmbrowser
    Version:               0.93.2 (7)
    App Item ID:           1007457278
    App External ID:       812659827
    Code Type:             X86-64 (Native)
    Parent Process:        ??? [1]
    Responsible:           Realm Browser [78299]
    User ID:               501

    Date/Time:             2015-08-06 11:15:19.276 -0400
    OS Version:            Mac OS X 10.10.4 (14E46)
    Report Version:        11
    Anonymous UUID:        D97EB571-3045-7E10-D89F-2FB0D4CF110D

    Time Awake Since Boot: 610000 seconds

    Crashed Thread:        0  Dispatch queue: com.apple.main-thread

    Exception Type:        EXC_CRASH (SIGABRT)
    Exception Codes:       0x0000000000000000, 0x0000000000000000

    Application Specific Information:
    abort() called

    Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
    0   libsystem_kernel.dylib          0x00007fff87bf6286 __pthread_kill + 10
    1   libsystem_c.dylib               0x00007fff91f2cb53 abort + 129
    2   org.cocoapods.Realm             0x000000010c23fbc9 please_report_this_error_to_help_at_realm_dot_io + 9
    3   org.cocoapods.Realm             0x000000010c23fd88 realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 328
    4   org.cocoapods.Realm             0x000000010c1f9917 realm::util::terminate(char const*, char const*, long) + 473
    5   org.cocoapods.Realm             0x000000010c350e22 realm::Table::update_accessors(unsigned long const*, unsigned long const*, realm::Table::AccessorUpdater&) + 290
    6   org.cocoapods.Realm             0x000000010c2f7bb5 void realm::_impl::TransactLogParser::do_parse<realm::Group::TransactAdvancer>(realm::Group::TransactAdvancer&) + 5285
    7   org.cocoapods.Realm             0x000000010c2f1248 realm::Group::advance_transact(unsigned long, unsigned long, realm::BinaryData const*, realm::BinaryData const*) + 168
    8   org.cocoapods.Realm             0x000000010c2fc0a3 realm::SharedGroup::advance_read(realm::SharedGroup::VersionID) + 355
    9   org.cocoapods.Realm             0x000000010c22d1f5 -[RLMRealm handleExternalCommit] + 124
    10  org.cocoapods.Realm             0x000000010c2301ae -[RLMNotifier listen]::$_0::__invoke(void*) + 38
    11  com.apple.CoreFoundation        0x00007fff87ccba01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    12  com.apple.CoreFoundation        0x00007fff87cbdb8d __CFRunLoopDoSources0 + 269
    13  com.apple.CoreFoundation        0x00007fff87cbd1bf __CFRunLoopRun + 927
    14  com.apple.CoreFoundation        0x00007fff87cbcbd8 CFRunLoopRunSpecific + 296
    15  com.apple.HIToolbox             0x00007fff8678056f RunCurrentEventLoopInMode + 235
    16  com.apple.HIToolbox             0x00007fff867801ee ReceiveNextEventCommon + 179
    17  com.apple.HIToolbox             0x00007fff8678012b _BlockUntilNextEventMatchingListInModeWithFilter + 71
    18  com.apple.AppKit                0x00007fff8e8008ab _DPSNextEvent + 978
    19  com.apple.AppKit                0x00007fff8e7ffe58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
    20  com.apple.AppKit                0x00007fff8e7f5af3 -[NSApplication run] + 594
    21  com.apple.AppKit                0x00007fff8e772244 NSApplicationMain + 1832
    22  libdyld.dylib                   0x00007fff882fc5c9 start + 1

    Thread 1:: Dispatch queue: com.apple.libdispatch-manager
    0   libsystem_kernel.dylib          0x00007fff87bf7232 kevent64 + 10
    1   libdispatch.dylib               0x00007fff8e38ca6a _dispatch_mgr_thread + 52

    Thread 2:
    0   libsystem_kernel.dylib          0x00007fff87bf694a __workq_kernreturn + 10
    1   libsystem_pthread.dylib         0x00007fff8b41040d start_wqthread + 13

    Thread 3:
    0   libsystem_kernel.dylib          0x00007fff87bf694a __workq_kernreturn + 10
    1   libsystem_pthread.dylib         0x00007fff8b41040d start_wqthread + 13

    Thread 4:
    0   libsystem_kernel.dylib          0x00007fff87bf694a __workq_kernreturn + 10
    1   libsystem_pthread.dylib         0x00007fff8b41040d start_wqthread + 13

    Thread 5:
    0   libsystem_kernel.dylib          0x00007fff87bf694a __workq_kernreturn + 10
    1   libsystem_pthread.dylib         0x00007fff8b41040d start_wqthread + 13

    Thread 6:
    0   libsystem_kernel.dylib          0x00007fff87bf694a __workq_kernreturn + 10
    1   libsystem_pthread.dylib         0x00007fff8b41040d start_wqthread + 13

    Thread 7:
    0   libsystem_kernel.dylib          0x00007fff87bf694a __workq_kernreturn + 10
    1   libsystem_pthread.dylib         0x00007fff8b41040d start_wqthread + 13

    Thread 8:
    0   libsystem_kernel.dylib          0x00007fff87bf694a __workq_kernreturn + 10
    1   libsystem_pthread.dylib         0x00007fff8b41040d start_wqthread + 13

    Thread 9:
    0   libsystem_kernel.dylib          0x00007fff87bf694a __workq_kernreturn + 10
    1   libsystem_pthread.dylib         0x00007fff8b41040d start_wqthread + 13

    Thread 10:
    0   libsystem_kernel.dylib          0x00007fff87bf694a __workq_kernreturn + 10
    1   libsystem_pthread.dylib         0x00007fff8b41040d start_wqthread + 13

    Thread 11:
    0   libsystem_kernel.dylib          0x00007fff87bf14de mach_msg_trap + 10
    1   libsystem_kernel.dylib          0x00007fff87bf064f mach_msg + 55
    2   com.apple.CoreFoundation        0x00007fff87cbdeb4 __CFRunLoopServiceMachPort + 212
    3   com.apple.CoreFoundation        0x00007fff87cbd37b __CFRunLoopRun + 1371
    4   com.apple.CoreFoundation        0x00007fff87cbcbd8 CFRunLoopRunSpecific + 296
    5   com.apple.AppKit                0x00007fff8e8c856b _NSEventThread + 137
    6   libsystem_pthread.dylib         0x00007fff8b412268 _pthread_body + 131
    7   libsystem_pthread.dylib         0x00007fff8b4121e5 _pthread_start + 176
    8   libsystem_pthread.dylib         0x00007fff8b41041d thread_start + 13

    Thread 12:: RLMRealm notification listener
    0   libsystem_kernel.dylib          0x00007fff87bf721a kevent + 10
    1   com.apple.Foundation            0x00007fff92584dc2 __NSThread__main__ + 1345
    2   libsystem_pthread.dylib         0x00007fff8b412268 _pthread_body + 131
    3   libsystem_pthread.dylib         0x00007fff8b4121e5 _pthread_start + 176
    4   libsystem_pthread.dylib         0x00007fff8b41041d thread_start + 13

    Thread 13:
    0   libsystem_kernel.dylib          0x00007fff87bf694a __workq_kernreturn + 10
    1   libsystem_pthread.dylib         0x00007fff8b41040d start_wqthread + 13

    Thread 0 crashed with X86 Thread State (64-bit):
      rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x00007fff53a4fcb8  rdx: 0x0000000000000000
      rdi: 0x000000000000130f  rsi: 0x0000000000000006  rbp: 0x00007fff53a4fce0  rsp: 0x00007fff53a4fcb8
       r8: 0x00007f99a991b000   r9: 0x0000000000000a00  r10: 0x0000000008000000  r11: 0x0000000000000206
      r12: 0x00007fff53a501c8  r13: 0x0000000000000014  r14: 0x00007fff75585300  r15: 0x0000000000000014
      rip: 0x00007fff87bf6286  rfl: 0x0000000000000206  cr2: 0x00007fff763e4fd8

    Logical CPU:     0
    Error Code:      0x02000148
    Trap Number:     133

**Comment by TimOliver** [comment]
Hi there!

Oh dear! I'm sorry to see that!

I just finished updating the Realm Browser build here with Realm 0.94 as well (The App Store version is still running v0.93).

Have you tried building a version of the Realm Browser from the code here and seeing if it still crashes?

If so, I'll need to expedite an update of the Realm Browser to the App Store as soon as possible.

**Comment by lionpants** [comment]
I'm trying to build the latest version via Xcode but can't due to code signing issues. Is there another method I am not aware of?

**Comment by TimOliver** [comment]
You should be able to turn the code-signing off if it's a local build (I might see if I can make them automatic in the settings).

**Comment by lionpants** [comment]
Cool, didn't know you could turn signing off.

Yup the latest version seems to work fine!

**Comment by TimOliver** [comment]
Excellent! I'm glad that fixed it!

We'll need to look at getting an update to the App Store integrating 0.94 quickly to ensure this doesn't happen to anyone else!

**Comment by TimOliver** [comment]
Actually, you know what? This issue shouldn't have been happening. 

I just tested a similar scenario with one of my own production Realm files, and it worked fine, and one of the developers just confirmed with me that nothing should have been changed between 0.93 and 0.94 to create a crash-level incompatibility.

It's possible you may have come across a small edge case that we should be looking into.

If possible, would you willing to send us the code that was causing this crash? 
Alternatively, if that's not possible/feasible, can you indicate what types of data you were trying to save into the Realm file, and what the write transaction block of code looked like?

Thanks a lot for that!

**Comment by lionpants** [comment]
I've managed to reproduce this in a small test app.

Steps to reproduce...
- Start the app
- Click the "Do Things" button, this will insert 10000 Animals into the Realm DB
- Open RealmBrowser 0.93.2 (7)
- Open the Realm DB file for the TestApp
- You should see the 10000 Animals and 4 Food objects
- Press the "Do Things" button again
- RealmBrowser should crash

TestApp...
http://dropcanvas.com/cqgw7

**Comment by TimOliver** [comment]
Awesome! Thank you so much for doing that! That's a huge help to us! 
I'll have a play with that sample app and see if I can uncover what's going on exactly.
Thanks again!

**Comment by TimOliver** [comment]
Alright. After discussing it with another one of the Cocoa engineers, we think this must be some kind of bug in Realm Objective-C itself that manifested between version 0.93 and 0.94.

I've re-uploaded the sample app, and mirrored the steps for reproduction in the Realm Cocoa repo (https://github.com/realm/realm-cocoa/issues/2432). We'll continue working it out from there.

Thanks again so much for reporting this issue, and taking the time to make a sample app! :)
