### ISSUE TITLE
Allow the use of 'CMD + A' to select all rows in a table

### ISSUE THREAD

**Issue by lionpants** [realm/realm-browser-osx#53]
Add the ability to select all rows in a table by pressing CMD+A allowing for quick deletion. Or better yet, a right click option in the Table List that would delete all rows in a table.

**Comment by TimOliver** [comment]
I added this yesterday. It's now possible to select all rows in a table, by either pressing cmd-A, or choosing 'Select All' from the 'Edit' menu.

It'll be available to download in a new update soon.
