### ISSUE TITLE
Improve the experience of the "Open Common Location" menu item

### ISSUE THREAD

**Issue by TimOliver** [realm/realm-browser-osx#59]
At present, the "Open Common Location" menu item scans all of the most common developer directories on a Mac (iPhone Simulator, Downloads etc) for .realm files.

The experience of this menu item isn't great. Indexing of .realm files is done on the main thread, and can be time-consuming, blocking the Realm Browser's UI.

A review of this feature and how it works should be undertaken, but at the very least, indexing should be moved to a background dispatch queue.

**Comment by EauSauvage** [comment]
Hi,
on my machine, all the sub menu items in "Open Common Location" are always grayed out, so I can't open the files on the simulator at all.
Realm Browser: 0.103.1 (75)

Realm version: ?

1.0.0

Xcode version: ?

7.3

**Comment by stel** [comment]
That was fixed in https://github.com/realm/realm-browser-osx/pull/186.
