### ISSUE TITLE
Y U NO USE TAGS?

### ISSUE THREAD

**Issue by ReDetection** [realm/realm-browser-osx#60]
Subject. :wink: 
It's easier to track current version here. https://github.com/realm/realm-browser-osx/releases 

And how soon can I see latest version in the Mac AppStore?

**Comment by TimOliver** [comment]
Thanks for the heads-up! I've added a tag for v0.93 for now. :)

Soon! I'm going to consolidate the feature I'm working on now (Encrypted Realm support) as well as update the Browser to use Realm 0.95 and then look at getting a release submitted after that.
