### ISSUE TITLE
El Capitan display issues

### ISSUE THREAD

**Issue by segiddins** [realm/realm-browser-osx#62]
![screen shot 2015-09-03 at 8 39 10 pm](https://cloud.githubusercontent.com/assets/1946610/9674361/28f9caf6-527e-11e5-9501-9126749c300d.png)

**Comment by TimOliver** [comment]
Thanks for that @segiddins! I'm looking into it now. 

It seems that El Capitan has changed the way view layout is handled, so the block of code handling the sizing/placement of those bubbles isn't getting called anymore.

**Comment by TimOliver** [comment]
Fixed and merged in!

**Comment by roothybrid7** [comment]
![2015-10-05 0 48 27](https://cloud.githubusercontent.com/assets/217229/10271565/e15d6a3a-6b4c-11e5-8e6e-293cb4144063.png)

I found an another El Capitan display issue.
I can resize a property column, but I don't see a property value with abbreviation.

**Comment by TimOliver** [comment]
Hi @roothybrid7! Thanks for reporting the issue!

Yeah, that's the same bug reported in issue https://github.com/realm/realm-browser-osx/issues/78 
It seems the view layout code has changed between Yosemite and El Capitan, but I'm still exploring how to correct it.
