### ISSUE TITLE
Search field not working

### ISSUE THREAD

**Issue by astigsen** [realm/realm-browser-osx#65]
The search field seems to be broken on version 0.93.2. Clicking on it does not allow you to write in it, so there is no way to search.

**Comment by TimOliver** [comment]
Thanks for that @astigsen! I just tested it on the latest version of the Browser, on both of my laptops running OS X El Capitan, and OS X Yosemite respectively, and it was working perfectly on both (Although, I wasn't happy with the search string being case-sensitive, so I just changed that: https://github.com/realm/realm-browser-osx/pull/104).

If this issue does manifest for you again on the latest version of the Browser, please let me know!
