### ISSUE TITLE
Weird editing behaviour on dates

### ISSUE THREAD

**Issue by astigsen** [realm/realm-browser-osx#67]
When editing dates it sometimes show up a small data picker, sometimes edits it as string. Seems a bit random depending on how you click on it.

**Comment by TimOliver** [comment]
Thanks for reporting this @astigsen! I researched this one on the weekend.

It looks like the data picker only appears when you double-click the table cell. If you single-click it, the standard system text field takes appears instead.

I'm tracking down in the code where these two states are managed so I can make sure they're standardised. :)
