### ISSUE TITLE
Release Realm Browser on the Mac App Store

### ISSUE THREAD

**Issue by TimOliver** [realm/realm-browser-osx#7]
_From @timanglade on April 6, 2015 5:55_

Since the browser is a relevant tool for users who otherwise don’t need to download realm-cocoa (e.g. Java developers, administrators, app designers, etc.), it makes sense at this point to distribute the browser on the app store (in addition to including it in our .zip realm-cocoa releases).

_Copied from original issue: realm/realm-cocoa#1733_

**Comment by timanglade** [comment]
To be clear I no longer feel we absolutely need to duplicate releasing both on the Mac App Store + in the .zips. As @jpsim mentioned on the call today, releasing on the Mac App Store (only thing we link in public) + having backup releases on Github (in case we need to rush-link to an emergency fix while waiting for the review process to complete) is probably the way to go.

**Comment by jpsim** [comment]
This was done over a month ago: https://itunes.apple.com/app/realm-browser/id1007457278
