### ISSUE TITLE
Realm Browser does not refresh when underlying data changes

### ISSUE THREAD

**Issue by azamsharp** [realm/realm-browser-osx#72]
Realm Browser does not automatically refresh when the underlying data changes due to insert, update, delete operation. I have to manually close the Realm Browser and then open it again to see the changes. 

Realm Browser 
Version 0.93.2 (7)

**Comment by jpsim** [comment]
Please make sure the Realm Browser is at the same version as the Realm framework in your application. If this is already the case, we'll need a bit more information to go on in order to identify what's happening.

Thanks!

**Comment by azamsharp** [comment]
I am using latest version of Realm and the Realm Browser that was available a week ago.

**Comment by DrJid** [comment]
Can confirm this bug. Using RealmSwift installed from Pods. And the data browser that's currently on the app store. After changing the underlying model, the data browser does not update

**Comment by DrJid** [comment]
Actually, Using this pre release realm browser fixes this issue. https://github.com/realm/realm-browser-osx/releases/tag/0.96-prerelease I guess the assumption that I downloaded the latest files from cocoapods and the app store makes you think they are the same versions.

**Comment by TimOliver** [comment]
Hi @DrJid!

Yep that's correct! If you're using the latest version of Realm in your app, you'll need that pre-release version of the Browser to open any files created with that version.

That version is currently in review with Apple and should be on the App Store within the next few days.

Thanks!
