### ISSUE TITLE
Realm Not Fetching Back References for an Object

### ISSUE THREAD

**Issue by azamsharp** [realm/realm-browser-osx#73]
I have objects like this: 

GroceryItem
tile 
groceryCategory 

AND 
GroceryCategory 
title 
let groceryItems = List<GroceryItem>() 

When I fetch the groceryItems like this: 

 self.groceryItems = realm.objects(GroceryItem).filter("shoppingList == %@", self.shoppingList).sorted("dateCreated", ascending: false)

It does not fetch the grocery categories associated with the grocery items. 

self.groceryItem[0].groceryCategory is always nil

When I print on the console it says "<Maximum depth exceeded>;" for groceryCategory.

**Comment by jpsim** [comment]
This query refers to properties that aren't present in your model:

```swift
self.groceryItems = realm.objects(GroceryItem).filter("shoppingList == %@", self.shoppingList).sorted("dateCreated", ascending: false)
```

According to your models, `GroceryItem` doesn't have a `shoppingList` or `dateCreated` property. So these queries should be throwing exceptions at runtime indicating this mismatch.

Perhaps the model definitions you posted are incomplete? If so, please post a more complete code example so we have more information to go on to help you.

Aside: I think you probably meant to post this on the https://github.com/realm/realm-cocoa repo, this is the repo for the Realm Browser (an OS X app to view Realm files that's *powered* by Realm Cocoa).
