### ISSUE TITLE
Realm Browser navigation doesn't always go "back" to the proper place

### ISSUE THREAD

**Issue by TimOliver** [realm/realm-browser-osx#8]
_From @webmagnets on April 20, 2015 20:59_

Here is a video that shows the unexpected behavior:

https://www.dropbox.com/s/6dtitwguo0pgr7e/realm%20navigation.mov?dl=0

_Copied from original issue: realm/realm-cocoa#1770_

**Comment by stel** [comment]
Closing this because it duplicates https://github.com/realm/realm-browser-osx/issues/182 that contains some more info about the issue.
