### ISSUE TITLE
Browser not working for realm database created using realm-java v0.83

### ISSUE THREAD

**Issue by katta** [realm/realm-browser-osx#85]
Using realm-java v0.83 and the realm browser fails to open the database. It says "Invalid Database" in a popup when I try to open a database.

To ensure the database is created properly, when I debug using the android app, am able to query the data I have inserted, hence I assume the database is created properly but the browser is not able to open it.

**Comment by TimOliver** [comment]
Hi @katta!

Ahh, yeah. That's to be expected for now. The latest version of Browser is built with Realm-Cocoa 0.95 which is running on a slightly older version of the Realm Core than the latest version of Realm-Java.

There's a beta branch of the Browser using the new 0.96 beta version of Realm-Cocoa, which I believe is using the latest version of the Core (But we're still testing it on the Cocoa side!).

Please try downloading this branch, building it and seeing if it then works for you:
https://github.com/realm/realm-browser-osx/tree/0.96-beta

(You'll need Xcode to build it. Let me know if you don't have Xcode installed.)

**Comment by marukami** [comment]
Can confirm that 0.96-beta works for realm-java v0.83.0

**Comment by katta** [comment]
I wasn't able to get it built on my machine. Is there any specific
instructions to build apart from the following

1. pod install
2. Build in xcode

-Katta

On Sat, Oct 10, 2015 at 4:45 PM, Mitchell Tilbrook <notifications@github.com

**Comment by marukami** [comment]
That's what I did. Though, I did have to use the GUI xcode, could not seem to build with the CLI.

what error did you get?

In case it helps I'm running
pod: 0.39.0
Xcode: 7.0.1

**Comment by katta** [comment]
Am using older version of xcode v6.x, will try with the newer version of xcode and update.

**Comment by TimOliver** [comment]
@katta If you're still having trouble, I've pre-built a version of the Ream Browser running the official version of 0.96 now: https://github.com/realm/realm-browser-osx/releases/tag/0.96-prerelease

Let me know if you need anymore help!

**Comment by TimOliver** [comment]
Thanks a lot for the feedback everyone!

Apple has approved v0.96 of the Browser, featuring the new file format, and it is officially live on the App Store now. Please be sure to update to it and let us know if you experience any issues with it.

https://itunes.apple.com/au/app/realm-browser/id1007457278?mt=12

Thanks!
