### ISSUE TITLE
Realm Browser crashes on certain data Type

### ISSUE THREAD

**Issue by brainray** [realm/realm-browser-osx#90]
Since either release 0.96 or Xcode 7.1 (can't tell) Realm Browser crashes when selecting a certain data type. I'm using the ObjC version. Please try to open the sidebar for "Menu".
The crash leads to terminate.hpp line 38.

The realm can be found here:
https://www.dropbox.com/s/z1brux2cp6bbnqn/Archive.zip?dl=0

**Comment by TimOliver** [comment]
Hi @brainray!
Thanks a lot for the report. I'll test it out on my end and see what's going on in there. :)

**Comment by brainray** [comment]
Hi @TimOliver ! To me it looks like this is fixed with the recent commit of 0.96 beta/ ff893e7

Thanks a lot :-)

Ray
