### ISSUE TITLE
v0.96.1 on GitHub is not signed with Developer ID

### ISSUE THREAD

**Issue by bdash** [realm/realm-browser-osx#93]
The v0.96.1 binary at https://github.com/realm/realm-browser-osx/releases appears to be signed with an App Store signing certificate:

```
mrowe@apollo:~$ spctl --assess -vv ~/Downloads/Realm\ Browser.app/
/Users/mrowe/Downloads/Realm Browser.app/: rejected
origin=Mac Developer: Bjarne Christiansen (NB6TA6AEJL)
```
This causes Gatekeeper to prevent the downloaded app from opening without extra steps from the user. If we're going to provide binaries, and we should since it's a good fallback for App Store review issues, we should be signing them with Developer ID.

**Comment by jpsim** [comment]
:+1:

**Comment by TimOliver** [comment]
Dang it! Thanks for that @bdash!

I'll look into properly signing and re-uploading a new version. Unfortunately, the Member Center seems to be down for the time being, so I'll keep checking back.

**Comment by TimOliver** [comment]
Alrighty! I've signed, and uploaded a new version of the Realm Browser to [Releases](https://github.com/realm/realm-browser-osx/releases).

```
spctl --assess -vv /Users/TiM/Desktop/Realm\ Browser\ 2015-11-18\ 17-16-18/Realm\ Browser.app 
/Users/TiM/Desktop/Realm Browser 2015-11-18 17-16-18/Realm Browser.app: accepted
source=Developer ID
origin=Developer ID Application: Realm ApS (QX5CR2FTN2)
```
